// Generated by CoffeeScript 1.7.1
(function() {
  var App, Background, BlabEvents, Buttons, Computation, ComputationButtons, ComputationEditor, Definitions, EditPageButton, Errors, GoogleAnalytics, Layout, Loader, MarkdownEditor, PopupEditorManager, Settings, TextEditor, Widget, WidgetEditor, Widgets, codeSections,
    __slice = [].slice,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  if (typeof $blab !== "undefined" && $blab !== null ? $blab.layoutProcessed : void 0) {
    return;
  }

  $blab.layoutProcessed = true;

  $blab.codeDecoration = true;

  Widget = (function() {
    Widget.handle = null;

    Widget.register = function(W) {
      return Widgets.register(W);
    };

    Widget.getWidget = function() {
      return Widgets.Registry[this.name];
    };

    Widget.getApi = function() {
      return "$blab.Widgets.Registry." + this.name;
    };

    Widget.layoutPreamble = function() {
      var W, api;
      W = this.getWidget();
      api = this.getApi();
      return "" + W.handle + " = (id, spec) -> new " + api + "(id, spec)";
    };

    Widget.computePreamble = function() {
      var W, api;
      W = this.getWidget();
      api = this.getApi();
      return "" + W.handle + " = (id, v...) ->\n  " + api + ".compute(id, v...)";
    };

    Widget.fetch = function() {
      var W, id, v;
      id = arguments[0], v = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      W = this.getWidget();
      return Widgets.fetch.apply(Widgets, [W, id].concat(__slice.call(v)));
    };

    Widget.getVal = function() {
      var id, v, _ref;
      id = arguments[0], v = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return (_ref = this.fetch.apply(this, [id].concat(__slice.call(v)))) != null ? _ref.getVal() : void 0;
    };

    Widget.setVal = function() {
      var id, v, _ref;
      id = arguments[0], v = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      if ((_ref = this.fetch.apply(this, [id].concat(__slice.call(v)))) != null) {
        _ref.setVal(v);
      }
      return null;
    };

    Widget.setValAndGet = function() {
      var id, v, _ref;
      id = arguments[0], v = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return (_ref = this.fetch.apply(this, [id].concat(__slice.call(v)))) != null ? _ref.setVal(v) : void 0;
    };

    Widget.domIdPrefix = function() {
      var W;
      W = this.getWidget();
      return W.handle + "-";
    };

    Widget.createDomId = function(prefix, id) {
      var domId;
      domId = prefix + id.split(" ").join("-");
      return domId;
    };

    function Widget(p1, p2) {
      this.p1 = p1;
      this.p2 = p2;
      this.used = false;
      if (typeof this.p1 === "string") {
        this.id = this.p1;
        this.spec = this.p2;
        this.spec.id = this.id;
      } else {
        this.spec = this.p1;
        this.id = this.spec.id;
      }
      if (typeof this.create === "function") {
        this.create(this.spec);
      }
    }

    Widget.prototype.appendToCanvas = function(mainContainer) {
      this.mainContainer = mainContainer;
      return Widgets.append(this.domId(), this, this.mainContainer);
    };

    Widget.prototype.domId = function() {
      return Widget.createDomId(this.constructor.domIdPrefix(), this.id);
    };

    Widget.prototype.select = function() {
      var type;
      type = this.constructor.handle;
      return $.event.trigger("clickWidget", {
        type: type,
        id: this.domId(),
        widget: this
      });
    };

    Widget.prototype.computeAll = function() {
      return Widgets.compute();
    };

    Widget.prototype.setUsed = function(used) {
      if (used == null) {
        used = true;
      }
      if (used === this.used) {
        return;
      }
      this.mainContainer.css({
        opacity: (used ? 1 : 0.2)
      });
      return this.used = used;
    };

    return Widget;

  })();

  Widgets = (function() {
    function Widgets() {}

    Widgets.filename = "layout.coffee";

    Widgets.Registry = {};

    Widgets.register = function(WidgetSet) {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = WidgetSet.length; _i < _len; _i++) {
        Widget = WidgetSet[_i];
        _results.push(this.Registry[Widget.name] = Widget);
      }
      return _results;
    };

    Widgets.widgets = {};

    Widgets.count = 0;

    Widgets.initialize = function() {
      this.Layout = Layout;
      if (this.widgetEditor == null) {
        this.widgetEditor = new WidgetEditor(this.filename);
      }
      $(document).on("aceFilesLoaded", (function(_this) {
        return function() {
          var resource;
          if (_this.widgetEditor.editor) {
            return;
          }
          resource = $blab.resources.find(_this.filename);
          return _this.widgetEditor.init(resource);
        };
      })(this));
      $(document).on("preCompileCoffee", (function(_this) {
        return function(evt, data) {
          var resource, url;
          resource = data.resource;
          url = resource.url;
          _this.count = 0;
          if (url !== _this.filename) {
            return;
          }
          _this.widgetEditor.init(resource);
          _this.precode();
          return _this.widgets = {};
        };
      })(this));
      $(document).on("compiledCoffeeScript", (function(_this) {
        return function(evt, data) {
          var err, key, widget, _i, _len, _ref;
          if (data.url !== _this.filename) {
            return;
          }
          err = $blab.windowError;
          $.event.trigger("layoutError", {
            source: _this.filename,
            error: err
          });
          $.event.trigger("blabError", {
            source: _this.filename,
            error: err
          });
          if (err) {
            $blab.windowError = false;
            return;
          }
          _ref = _this.widgets;
          for (widget = _i = 0, _len = _ref.length; _i < _len; widget = ++_i) {
            key = _ref[widget];
            if (widget != null) {
              if (typeof widget.initialize === "function") {
                widget.initialize();
              }
            }
          }
          Computation.init();
          return $.event.trigger("htmlOutputUpdated");
        };
      })(this));
      return this.queueCompile(2000);
    };

    Widgets.append = function(id, widget, element) {
      this.widgets[id] = widget;
      return this.Layout.append(element, widget);
    };

    Widgets.fetch = function() {
      var Widget, id, id2, idSpecified, prefix, v, w;
      Widget = arguments[0], id = arguments[1], v = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
      idSpecified = id != null;
      if (!idSpecified) {
        id = this.count;
        this.count++;
      }
      prefix = Widget.domIdPrefix();
      id2 = prefix ? Widget.createDomId(prefix, id) : id;
      w = this.widgets[id2];
      if (w) {
        return w;
      }
      if (idSpecified) {
        this.createFromId.apply(this, [Widget, id].concat(__slice.call(v)));
      } else {
        this.createFromCounter.apply(this, [Widget, id].concat(__slice.call(v)));
      }
      return null;
    };

    Widgets.createFromId = function() {
      var Widget, code, id, name, resource, s, spec, v;
      Widget = arguments[0], id = arguments[1], v = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
      resource = $blab.resources.find(this.filename);
      name = Widget.handle;
      spec = Widget.initSpec(id, v);
      s = spec.split("\n").join("\n  ");
      code = "" + name + " \"" + id + "\",\n  " + s + "\n";
      resource.containers.fileNodes[0].editor.set(resource.content + "\n" + code);
      return this.queueCompile();
    };

    Widgets.createFromCounter = function() {
      var Widget, id, make, spec, v;
      Widget = arguments[0], id = arguments[1], v = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
      spec = Widget.initSpec(id, v);
      make = function() {
        return new Widget(id, eval(CoffeeScript.compile(spec, {
          bare: true
        })));
      };
      return setTimeout(make, 700);
    };

    Widgets.queueCompile = function(t) {
      var resource;
      if (t == null) {
        t = 500;
      }
      resource = $blab.resources.find(this.filename);
      if (this.tCompile) {
        clearTimeout(this.tCompile);
        this.tCompile = null;
      }
      return this.tCompile = setTimeout(((function(_this) {
        return function() {
          resource.compile();
          return $.event.trigger("layoutCompiled");
        };
      })(this)), t);
    };

    Widgets.compute = function() {
      return Computation.compute();
    };

    Widgets.precode = function() {
      var W, n, preamble, precompile, _ref;
      preamble = Layout.shortcuts + "\n";
      _ref = this.Registry;
      for (n in _ref) {
        W = _ref[n];
        preamble += W.layoutPreamble() + "\n";
      }
      precompile = {};
      precompile[this.filename] = {
        preamble: preamble,
        postamble: ""
      };
      return $blab.precompile(precompile);
    };

    Widgets.getFromSignature = function(handle, id) {
      var name, prefix, widget, _ref;
      _ref = this.Registry;
      for (name in _ref) {
        Widget = _ref[name];
        if (Widget.handle !== handle) {
          continue;
        }
        prefix = Widget.domIdPrefix();
        if (prefix) {
          id = Widget.createDomId(prefix, id);
        }
        widget = this.widgets[id];
        break;
      }
      return widget != null ? widget : null;
    };

    Widgets.setAllUnused = function() {
      var id, w, _ref, _results;
      _ref = this.widgets;
      _results = [];
      for (id in _ref) {
        w = _ref[id];
        _results.push(w.setUsed(false));
      }
      return _results;
    };

    return Widgets;

  })();

  WidgetEditor = (function() {
    function WidgetEditor(filename) {
      this.filename = filename;
      this.firstDisplay = true;
      this.currentLine = null;
      this.viewPortDisplayed = false;
      this.sliding = false;
      this.next = (function(_this) {
        return function() {};
      })(this);
      this.shown = false;
      this.observers = {
        setViewPort: [],
        clickDelete: [],
        clickCloseButton: []
      };
    }

    WidgetEditor.prototype.init = function(resource) {
      var _ref, _ref1;
      this.resource = resource;
      if (this.editor) {
        return;
      }
      this.editor = (_ref = this.resource.containers) != null ? (_ref1 = _ref.fileNodes) != null ? _ref1[0].editor : void 0 : void 0;
      if (!this.editor) {
        return;
      }
      this.aceEditor = this.editor.editor;
      this.setViewPort(null);
      this.editor.onChange((function(_this) {
        return function() {};
      })(this));
      this.aceEditor.setShowFoldWidgets(true);
      this.container = this.editor.container;
      this.parent = this.container.parent();
      this.closeButton = new $blab.utils.CloseButton(this.parent, (function(_this) {
        return function() {
          return _this.trigger("clickCloseButton");
        };
      })(this));
      return this.closeButton.css({
        right: 30
      });
    };

    WidgetEditor.prototype.setViewPort = function(txt) {
      if (!this.editor) {
        return;
      }
      this.viewPortDisplayed = txt !== null;
      this.trigger("setViewPort");
      this.container = this.editor.container;
      this.parent = this.container.parent();
      if (this.firstDisplay) {
        this.container.removeClass("init-editor");
        this.container.css({
          maxHeight: "0px"
        });
        this.parent.show();
        this.editor.show(true);
        if (txt) {
          this.vp(txt, true);
        } else {
          setTimeout(((function(_this) {
            return function() {
              return _this.parent.hide();
            };
          })(this)), 1000);
        }
        return this.firstDisplay = false;
      } else {
        if (this.sliding) {
          return this.next = (function(_this) {
            return function() {
              _this.vp(txt);
              return _this.next = function() {};
            };
          })(this);
        } else {
          return this.vp(txt);
        }
      }
    };

    WidgetEditor.prototype.vp = function(txt, first) {
      var code, idx, line, lines, spec, _i, _len;
      if (first == null) {
        first = false;
      }
      this.container.css({
        maxHeight: "",
        border: "3px solid #aaf"
      });
      this.start = null;
      spec = this.editor.spec;
      if (txt) {
        code = this.editor.code();
        lines = code.split("\n");
        for (idx = _i = 0, _len = lines.length; _i < _len; idx = ++_i) {
          line = lines[idx];
          if (line.indexOf(txt) !== -1) {
            this.start = idx;
          }
          if ((this.start != null) && line === "") {
            this.end = idx;
            break;
          }
        }
      }
      if (this.start === null) {
        this.editor.spec.viewPort = false;
        this.sliding = true;
        this.parent.slideUp(400, (function(_this) {
          return function() {
            _this.sliding = false;
            return _this.next();
          };
        })(this));
        return;
      }
      if (!this.parent.hasClass("popup-editor")) {
        this.parent.addClass("popup-editor");
      }
      this.parent.css({
        maxHeight: "0px"
      });
      this.parent.show();
      this.deleteButton();
      this.errorMessage();
      if (this.start) {
        this.editor.show(true);
      }
      spec.viewPort = true;
      spec.startLine = this.start + 1;
      spec.endLine = this.end - this.start + 1 < 20 ? this.end + 1 : this.start + 20;
      this.editor.setViewPort();
      this.editor.editorContainer[0].onwheel = function() {
        return false;
      };
      this.parent.hide();
      this.parent.css({
        maxHeight: ""
      });
      this.sliding = true;
      return this.parent.slideDown(400, (function(_this) {
        return function() {
          _this.sliding = false;
          return _this.next();
        };
      })(this));
    };

    WidgetEditor.prototype.deleteButton = function() {
      var widget, _ref, _ref1;
      if ((_ref = this.del) != null) {
        _ref.empty();
      }
      if (!this.currentId) {
        return;
      }
      widget = Widgets.widgets[this.currentId];
      if (widget.used) {
        return;
      }
      if (!((_ref1 = this.del) != null ? _ref1.length : void 0)) {
        this.del = $("<div>", {
          css: {
            position: "absolute",
            display: "inline-block",
            top: 5,
            right: 15
          }
        });
        this.editor.editorContainer.append(this.del);
      }
      this.delButton = $("<span>", {
        text: "Delete",
        css: {
          cursor: "pointer"
        },
        click: (function(_this) {
          return function() {
            var selection;
            selection = _this.aceEditor.selection;
            if (!(_this.start && _this.end)) {
              return;
            }
            selection.moveCursorTo(_this.start - 1, 0);
            selection.selectTo(_this.end, 0);
            _this.aceEditor.removeLines();
            _this.editor.run();
            _this.parent.hide();
            return _this.trigger("clickDelete");
          };
        })(this)
      });
      return this.del.append(this.delButton);
    };

    WidgetEditor.prototype.errorMessage = function() {
      var _ref, _ref1;
      if ((_ref = this.message) != null) {
        _ref.empty();
      }
      if (!((_ref1 = this.message) != null ? _ref1.length : void 0)) {
        this.message = $("<div>", {
          css: {
            position: "absolute",
            display: "inline-block",
            top: 5,
            right: 15,
            color: "red"
          }
        });
        return this.editor.editorContainer.append(this.message);
      }
    };

    WidgetEditor.prototype.folding = function() {
      var ed, editor, resource, session, _ref, _ref1;
      resource = $blab.resources.find(this.filename);
      ed = (_ref = resource.containers) != null ? (_ref1 = _ref.fileNodes) != null ? _ref1[0].editor : void 0 : void 0;
      if (!ed) {
        return;
      }
      return;
      editor = ed.editor;
      editor.setShowFoldWidgets(true);
      session = editor.getSession();
      session.on("changeFold", function() {
        return ed.setHeight(session.getScreenLength());
      });
      return session.foldAll(1, 10000, 0);
    };

    WidgetEditor.prototype.on = function(evt, observer) {
      return this.observers[evt].push(observer);
    };

    WidgetEditor.prototype.trigger = function(evt, data) {
      var observer, _i, _len, _ref, _results;
      _ref = this.observers[evt];
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        observer = _ref[_i];
        _results.push(observer(data));
      }
      return _results;
    };

    return WidgetEditor;

  })();

  Computation = (function() {
    function Computation() {}

    Computation.filename = "compute.coffee";

    Computation.init = function() {
      var p;
      p = this.precode();
      if (!this.initialized) {
        $(document).on("allBlabDefinitionsLoaded", (function(_this) {
          return function(evt, data) {
            _this.defs = data.list;
            _this.precode();
            _this.initialized = true;
            return _this.compute();
          };
        })(this));
      }
      return this.compute();
    };

    Computation.compute = function() {
      var resource;
      resource = $blab.resources.find(this.filename);
      return resource != null ? resource.compile() : void 0;
    };

    Computation.precode = function() {
      var W, WidgetName, preamble, precompile, _ref;
      preamble = "";
      _ref = Widgets.Registry;
      for (WidgetName in _ref) {
        W = _ref[WidgetName];
        preamble += W.computePreamble() + "\n";
      }
      if (this.defs) {
        preamble += this.defs + "\n";
      }
      precompile = {};
      precompile[this.filename] = {
        preamble: preamble,
        postamble: ""
      };
      $blab.precompile(precompile);
      return true;
    };

    return Computation;

  })();

  ComputationEditor = (function() {
    ComputationEditor.prototype.filename = "compute.coffee";

    ComputationEditor.prototype.code = {
      slider: "x = slider \"x\"",
      plot: "plot \"my-plot\", x, y",
      table: "table \"my-table\", x, y"
    };

    function ComputationEditor() {
      this.setLine = __bind(this.setLine, this);
      this.currentLine = null;
      this.observers = {
        cursorOnWidget: []
      };
      $("#computation-code-heading").html("Computation <div id='computation-hint' class='code-hint'>Press shift-enter to run</div>");
      this.hint = $("#computation-hint");
      this.hint.hide();
      $(document).on("preCompileCoffee", (function(_this) {
        return function(evt, data) {
          var resource, url;
          resource = data.resource;
          url = resource != null ? resource.url : void 0;
          if (url === _this.filename) {
            return _this.init(resource);
          }
        };
      })(this));
      $(document).on("compiledCoffeeScript", (function(_this) {
        return function(evt, data) {
          if (data.url !== _this.filename) {

          }
        };
      })(this));
      $(document).on("clickComputationButton", (function(_this) {
        return function(evt, data) {
          _this.aceEditor.focus();
          return _this.aceEditor.insert(_this.code[data.button] + "\n");
        };
      })(this));
      $(document).on("runCode", (function(_this) {
        return function(evt, data) {
          if (data.filename !== _this.filename) {
            return;
          }
          _this.currentLine = null;
          return setTimeout((function() {
            return _this.setLine();
          }), 400);
        };
      })(this));
      $(document).on("allBlabDefinitionsLoaded", function() {});
      this.changeCursor = (function(_this) {
        return function() {};
      })(this);
    }

    ComputationEditor.prototype.init = function(resource) {
      var _ref, _ref1, _ref2;
      this.resource = resource;
      if (this.editor) {
        return;
      }
      this.editor = (_ref = this.resource) != null ? (_ref1 = _ref.containers) != null ? (_ref2 = _ref1.fileNodes) != null ? _ref2[0].editor : void 0 : void 0 : void 0;
      if (!this.editor) {
        return;
      }
      this.aceEditor = this.editor.editor;
      this.currentLine = null;
      this.selection = this.aceEditor.selection;
      return this.selection.on("changeCursor", (function(_this) {
        return function() {
          return _this.changeCursor();
        };
      })(this));
    };

    ComputationEditor.prototype.initFocusBlur = function() {
      this.aceEditor.on("focus", (function(_this) {
        return function() {
          _this.setLine(true);
          _this.changeCursor = function() {
            return _this.setLine();
          };
          return _this.hint.fadeIn();
        };
      })(this));
      return this.aceEditor.on("blur", (function(_this) {
        return function() {
          _this.hint.fadeOut();
          _this.currentLine = null;
          return _this.changeCursor = function() {};
        };
      })(this));
    };

    ComputationEditor.prototype.setLine = function(force) {
      var cursor, _ref;
      cursor = (_ref = this.selection) != null ? _ref.getCursor() : void 0;
      if (force || (cursor != null ? cursor.row : void 0) !== this.currentLine) {
        this.currentLine = cursor != null ? cursor.row : void 0;
        return this.inspectLineForWidget();
      }
    };

    ComputationEditor.prototype.insertCode = function(code) {
      this.aceEditor.focus();
      return this.aceEditor.insert(code);
    };

    ComputationEditor.prototype.inspectLineForWidget = function() {
      var WidgetName, code, handles, handlesStr, id, line, lines, match, matchArray, type, widgetRegex;
      if (!this.editor) {
        return;
      }
      code = this.editor.code();
      lines = code.split("\n");
      line = lines[this.currentLine];
      handles = (function() {
        var _ref, _results;
        _ref = Widgets.Registry;
        _results = [];
        for (WidgetName in _ref) {
          Widget = _ref[WidgetName];
          _results.push(Widget.handle);
        }
        return _results;
      })();
      handlesStr = handles.join("|");
      widgetRegex = new RegExp("(" + handlesStr + ") \"([^\"]*)\"", "g");
      matchArray = widgetRegex.exec(line);
      match = matchArray === null ? null : matchArray[0];
      type = matchArray === null ? null : matchArray[1];
      id = matchArray === null ? null : matchArray[2];
      if (this.tId) {
        clearTimeout(this.tId);
        this.tId = null;
      }
      return this.tId = setTimeout(((function(_this) {
        return function() {
          var widget;
          widget = Widgets.getFromSignature(type, id);
          return _this.trigger("cursorOnWidget", {
            widget: widget,
            match: match
          });
        };
      })(this)), 200);
    };

    ComputationEditor.prototype.on = function(evt, observer) {
      return this.observers[evt].push(observer);
    };

    ComputationEditor.prototype.trigger = function(evt, data) {
      var observer, _i, _len, _ref, _results;
      _ref = this.observers[evt];
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        observer = _ref[_i];
        _results.push(observer(data));
      }
      return _results;
    };

    return ComputationEditor;

  })();

  ComputationButtons = (function() {
    function ComputationButtons() {
      var run;
      this.container = $("#computation-buttons");
      run = $("<div>", {
        css: {
          display: "inline-block",
          color: "#aaa",
          fontSize: "10pt"
        },
        text: "Press shift-enter to run"
      });
      this.container.append(run);
    }

    ComputationButtons.prototype.create = function(txt) {
      var b;
      b = $("<button>", {
        text: txt
      });
      this.container.append(b);
      return b.click(function() {
        return $.event.trigger("clickComputationButton", {
          button: txt
        });
      });
    };

    return ComputationButtons;

  })();

  MarkdownEditor = (function() {
    MarkdownEditor.prototype.containerId = "#main-markdown";

    MarkdownEditor.prototype.filename = "blab.md";

    MarkdownEditor.prototype.markedUrl = "/puzlet/puzlet/js/marked.min.js";

    MarkdownEditor.prototype.posAttr = "data-pos";

    MarkdownEditor.prototype.widgetsId = "#widgets-container";

    MarkdownEditor.prototype.editorHeight = 15;

    function MarkdownEditor() {
      this.markdownDiv = __bind(this.markdownDiv, this);
      this.text = $(this.containerId);
      if (!this.text.length) {
        return;
      }
      this.text.css({
        cursor: "default"
      });
      this.text.mouseup((function(_this) {
        return function(evt) {
          return _this.trigger("clickText", {
            evt: evt,
            start: 0
          });
        };
      })(this));
      this.resources = $blab.resources;
      this.widgetsRendered = false;
      this.firstDisplay = true;
      this.viewPortDisplayed = false;
      this.observers = {
        initialized: [],
        setViewPort: [],
        clickText: [],
        clickCloseButton: []
      };
    }

    MarkdownEditor.prototype.setWidgetsRendered = function() {
      this.widgetsRendered = true;
      if (typeof marked !== "undefined" && marked !== null) {
        return this.process();
      }
    };

    MarkdownEditor.prototype.init = function() {
      var _ref, _ref1, _ref2;
      console.log("MarkdownEditor::init");
      marked.setOptions({
        renderer: new marked.Renderer,
        gfm: true,
        tables: true,
        breaks: false,
        pedantic: false,
        sanitize: false,
        smartLists: true,
        smartypants: false
      });
      this.customizeLinks();
      this.resource = this.resources.find(this.filename);
      this.editor = (_ref = this.resource) != null ? (_ref1 = _ref.containers) != null ? (_ref2 = _ref1.fileNodes) != null ? _ref2[0].editor : void 0 : void 0 : void 0;
      if (!this.editor) {
        return;
      }
      this.aceEditor = this.editor.editor;
      this.container = this.editor.container;
      this.parent = this.container.parent();
      this.container.removeClass("init-editor");
      this.editor.onChange((function(_this) {
        return function() {
          return _this.render();
        };
      })(this));
      this.editor.show(false);
      this.closeButton = new $blab.utils.CloseButton(this.parent, (function(_this) {
        return function() {
          return _this.trigger("clickCloseButton");
        };
      })(this));
      this.closeButton.css({
        right: 30
      });
      this.setViewPort(null);
      if (this.widgetsRendered) {
        this.process();
      }
      return this.trigger("initialized");
    };

    MarkdownEditor.prototype.customizeLinks = function() {
      return marked.Renderer.prototype.link = function(href, title, text) {
        var out, prot, t;
        if (this.options.sanitize) {
          try {
            prot = decodeURIComponent(unescape(href)).replace(/[^\w:]/g, '').toLowerCase();
          } catch (_error) {
            return '';
          }
          if (prot.indexOf('javascript:') === 0 || prot.indexOf('vbscript:') === 0) {
            return '';
          }
        }
        t = title ? " title=\"" + title + "\"" : "";
        return out = "<a href=\"" + href + "\" target=\"_blank\"" + t + ">" + text + "</a>";
      };
    };

    MarkdownEditor.prototype.preProcess = function(file) {
      var codeRe, escCodeMath, escMarkdown, escRe, matchEscape, preText, texRe, text, textCodeEsc, textMdEsc;
      preText = file.replace(/\\\$/g, "\\&pound;").replace(/\\`/g, "\\&sect;").replace(/([^-])([-]{3})([^-])/g, "$1&mdash;$3");
      matchEscape = function(text, RE, escape) {
        var escMatch, match, out, pos, preMatch;
        out = "";
        pos = 0;
        while ((match = RE.exec(text)) !== null) {
          preMatch = text.slice(pos, match.index);
          escMatch = escape(match[0]);
          out += preMatch + escMatch;
          pos = match.index + match[0].length;
        }
        return out += text.slice(pos);
      };
      escCodeMath = function(u) {
        return u.replace(/\$/g, function(m) {
          return "\\&yen;";
        });
      };
      codeRe = /(```)([\s\S]*?)(```)|(`)([\s\S]*?)(`)/mg;
      textCodeEsc = matchEscape(preText, codeRe, escCodeMath);
      escRe = /[\\`\*_\{\}\[\]\(\)#\+\-\.\!]/g;
      escMarkdown = function(u) {
        return u.replace(escRe, function(m) {
          return "\\" + m;
        });
      };
      texRe = /(\$\$)([\s\S]*?)(\$\$)|(\$)([\s\S]*?)(\$)/mg;
      textMdEsc = matchEscape(textCodeEsc, texRe, escMarkdown);
      text = textMdEsc.replace(/\\&pound;/g, "\\$").replace(/\\&sect;/g, "\\`").replace(/\\&yen;/g, "$");
      return text;
    };

    MarkdownEditor.prototype.process = function() {
      var container, m, md, out, _i, _len;
      console.log("MarkdownEditor::process");
      if (typeof marked === "undefined" || marked === null) {
        this.loadMarked((function(_this) {
          return function() {
            return _this.init();
          };
        })(this));
        return;
      }
      this.text.empty();
      $(".rendered-markdown").remove();
      md = this.snippets(this.preProcess(this.resource.content));
      out = [];
      for (_i = 0, _len = md.length; _i < _len; _i++) {
        m = md[_i];
        if (m.pos === 0) {
          this.text.append(m.html);
          out.push(m.html);
        } else {
          container = Layout.getContainer(m.pos, m.order);
          this.markdownDiv(container, m);
        }
      }
      this.setTitle(out.join("\n"));
      $.event.trigger("htmlOutputUpdated");
      return this.trigger("setViewPort");
    };

    MarkdownEditor.prototype.loadMarked = function(callback) {
      console.log("MarkdownEditor::loadMarked");
      this.resources.add({
        url: this.markedUrl
      });
      return this.resources.loadUnloaded(function() {
        return typeof callback === "function" ? callback() : void 0;
      });
    };

    MarkdownEditor.prototype.markdownDiv = function(container, m) {
      var div;
      div = $("<div>", {
        "class": "rendered-markdown",
        css: {
          cursor: "default"
        },
        mouseup: (function(_this) {
          return function(evt) {
            return _this.trigger("clickText", {
              evt: evt,
              start: parseInt(div.attr("data-start"))
            });
          };
        })(this)
      });
      div.attr({
        "data-pos": m.pos,
        "data-order": m.order,
        "data-start": m.start
      });
      div.append(m.html);
      container.append(div);
      return div;
    };

    MarkdownEditor.prototype.setTitle = function() {
      var headings;
      headings = $(":header");
      $blab.title = headings.length ? headings[0].innerHTML : "Puzlet";
      console.log("MarkdownEditor::setTitle", $blab.title);
      if ($blab.title !== "Untitled") {
        return document.title = $blab.title;
      }
    };

    MarkdownEditor.prototype.setViewPort = function(start) {
      if (!this.editor) {
        return;
      }
      this.viewPortDisplayed = start !== null && start !== false;
      this.trigger("setViewPort");
      this.container = this.editor.container;
      this.parent = this.container.parent();
      if (this.firstDisplay) {
        this.container.removeClass("init-editor");
        this.container.css({
          maxHeight: "0px"
        });
        this.parent.show();
        this.editor.show(true);
        setTimeout(((function(_this) {
          return function() {
            return _this.vp(start, true);
          };
        })(this)), 500);
        return this.firstDisplay = false;
      } else {
        return this.vp(start);
      }
    };

    MarkdownEditor.prototype.vp = function(startChar, first) {
      var spec;
      if (first == null) {
        first = false;
      }
      this.container.css({
        maxHeight: "",
        border: "3px solid #aaf"
      });
      spec = this.editor.spec;
      spec.viewPort = true;
      if (startChar === null || startChar === false) {
        spec.startLine = 1;
        spec.endLine = this.editorHeight;
        this.editor.setViewPort();
        if (first) {
          this.editor.show(false);
          this.parent.hide();
        } else {
          this.parent.slideUp(400);
        }
        return;
      }
      if (!this.parent.hasClass("popup-editor")) {
        this.parent.addClass("popup-editor");
      }
      this.start = (startChar === 0 ? 0 : this.getStartLine(startChar));
      this.end = this.start + this.editorHeight - 1;
      if (first) {
        this.parent.show();
      } else {
        this.parent.slideDown(400);
      }
      this.editor.show(true);
      spec.startLine = this.start + 1;
      spec.endLine = this.end + 1;
      return this.editor.setViewPort();
    };

    MarkdownEditor.prototype.getStartLine = function(startChar) {
      var code, idx, l, line, lines, _i, _len;
      code = this.editor.code();
      lines = code.split("\n");
      l = 0;
      for (idx = _i = 0, _len = lines.length; _i < _len; idx = ++_i) {
        line = lines[idx];
        l += line.length + 1;
        if (l > startChar) {
          break;
        }
      }
      return idx - 1;
    };

    MarkdownEditor.prototype.render = function() {
      if (this.renderId == null) {
        this.renderId = null;
      }
      if (this.renderId) {
        clearTimeout(this.renderId);
      }
      return this.renderId = setTimeout(((function(_this) {
        return function() {
          return _this.process();
        };
      })(this)), 500);
    };

    MarkdownEditor.prototype.snippets = function(file) {
      var found, match, md, snippet;
      if (this.RE == null) {
        this.RE = /^\s*`\s*(?:p|pos)\s*:\s*(\d+)\s*,?\s*(?:(?:o|ord|order)\s*:\s*(\d+)\s*)?.*`.*$/mg;
      }
      md = [];
      snippet = function(found) {
        var source, start, _ref, _ref1, _ref2;
        start = (_ref = found.start) != null ? _ref : 0;
        source = file.slice(start, +found.end + 1 || 9e9);
        return {
          start: start,
          pos: parseInt((_ref1 = found.pos) != null ? _ref1 : 0),
          order: parseInt((_ref2 = found.order) != null ? _ref2 : 1),
          source: source,
          html: marked(source)
        };
      };
      found = {};
      while ((match = this.RE.exec(file)) !== null) {
        found.end = match.index - 1;
        md.push(snippet(found));
        found = {
          start: match.index + match[0].length + 1,
          pos: match[1],
          order: match[2]
        };
      }
      found.end = -1;
      md.push(snippet(found));
      return md;
    };

    MarkdownEditor.prototype.on = function(evt, observer) {
      return this.observers[evt].push(observer);
    };

    MarkdownEditor.prototype.trigger = function(evt, data) {
      var observer, _i, _len, _ref, _results;
      _ref = this.observers[evt];
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        observer = _ref[_i];
        _results.push(observer(data));
      }
      return _results;
    };

    return MarkdownEditor;

  })();

  Layout = (function() {
    function Layout() {}

    Layout.shortcuts = "layout = (spec) -> $blab.Widgets.Layout.set(spec)\nsettings = (spec) -> $blab.blabrApp.setSettings(spec)\npos = (spec) -> $blab.Widgets.Layout.pos(spec)\ntext = (spec) -> $blab.Widgets.Layout.text(spec)";

    Layout.spec = {};

    Layout.currentContainer = null;

    Layout.observers = {
      renderedWidgets: [],
      clickBox: []
    };

    Layout.set = function(spec) {
      this.spec = spec;
      return this.render();
    };

    Layout.pos = function(currentContainer) {
      this.currentContainer = currentContainer;
    };

    Layout.render = function() {
      var c, col, d, label, n, o, r, row, widgets, _i, _j, _len, _ref;
      if (Array.isArray(this.spec)) {
        this.renderFromArray();
        return;
      }
      if (!Object.keys(this.spec).length) {
        return;
      }
      n = 1;
      widgets = $("#widgets-container");
      widgets.empty();
      _ref = this.spec;
      for (label in _ref) {
        row = _ref[label];
        r = $("<div>", {
          id: label
        });
        widgets.append(r);
        for (_i = 0, _len = row.length; _i < _len; _i++) {
          col = row[_i];
          c = $("<div>", {
            "class": col,
            mouseup: (function(_this) {
              return function(evt) {
                return _this.trigger("clickBox", {
                  evt: evt
                });
              };
            })(this)
          });
          c.addClass("layout-box");
          this.appendNum(c, n);
          n++;
          r.append(c);
          for (d = _j = 1; _j <= 5; d = ++_j) {
            o = $("<div>", {
              "class": "order-" + d
            });
            c.append(o);
          }
        }
        r.append($("<div>", {
          "class": "clear"
        }));
      }
      if (WidgetEditor.viewPortDisplayed || MarkdownEditor.viewPortDisplayed) {
        this.highlight();
      }
      return this.trigger("renderedWidgets");
    };

    Layout.renderFromArray = function() {
      var boxClass, boxId, c, colNum, d, n, numCols, o, r, rowIdx, widgets, _i, _j, _k, _len, _ref;
      if (!this.spec.length) {
        return;
      }
      n = 1;
      widgets = $("#widgets-container");
      widgets.empty();
      _ref = this.spec;
      for (rowIdx = _i = 0, _len = _ref.length; _i < _len; rowIdx = ++_i) {
        numCols = _ref[rowIdx];
        if (numCols > 4) {
          console.log("Maximum of 4 columns per row");
          numCols = 4;
        }
        r = $("<div>", {
          id: "widget-row-" + (rowIdx + 1)
        });
        widgets.append(r);
        for (colNum = _j = 1; 1 <= numCols ? _j <= numCols : _j >= numCols; colNum = 1 <= numCols ? ++_j : --_j) {
          boxId = "widget-box-" + n;
          boxClass = "box-" + numCols + "-" + colNum;
          c = $("<div>", {
            id: boxId,
            "class": boxClass,
            mouseup: (function(_this) {
              return function(evt) {
                return _this.trigger("clickBox", {
                  evt: evt
                });
              };
            })(this)
          });
          c.addClass("layout-box");
          r.append(c);
          this.appendNum(c, n);
          n++;
          for (d = _k = 1; _k <= 5; d = ++_k) {
            o = $("<div>", {
              "class": "order-" + d
            });
            c.append(o);
          }
        }
        r.append($("<div>", {
          "class": "clear"
        }));
      }
      if (WidgetEditor.viewPortDisplayed || MarkdownEditor.viewPortDisplayed) {
        this.highlight();
      }
      return this.trigger("renderedWidgets");
    };

    Layout.appendNum = function(c, n) {
      var num;
      num = $("<div>", {
        text: n,
        "class": "layout-box-number",
        css: {
          marginLeft: c.width() - 23
        }
      });
      c.append(num);
      return num.hide();
    };

    Layout.highlight = function(highlight) {
      if (highlight == null) {
        highlight = true;
      }
      if (highlight) {
        $(".layout-box").addClass("layout-highlight");
        return $(".layout-box-number").show();
      } else {
        $(".layout-box-number").hide();
        return $(".layout-box").removeClass("layout-highlight");
      }
    };

    Layout.append = function(element, widget) {
      var container;
      if ((widget != null ? widget.spec.pos : void 0) != null) {
        container = this.getContainer(widget.spec.pos, widget.spec.order);
      } else {
        container = $(this.currentContainer);
      }
      return container.append(element);
    };

    Layout.getContainer = function(pos, order) {
      var container, position;
      if ($.isNumeric(pos)) {
        position = "#widget-box-" + pos;
      } else {
        position = pos;
      }
      container = $(position);
      if (order != null) {
        container = $(container).find(".order-" + order);
      }
      return container;
    };

    Layout.text = function(t) {
      return this.append(t);
    };

    Layout.on = function(evt, observer) {
      return this.observers[evt].push(observer);
    };

    Layout.trigger = function(evt, data) {
      var observer, _i, _len, _ref, _results;
      _ref = this.observers[evt];
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        observer = _ref[_i];
        _results.push(observer(data));
      }
      return _results;
    };

    return Layout;

  })();

  Definitions = (function() {
    Definitions.prototype.filename = "defs.coffee";

    function Definitions(done) {
      this.done = done;
      $("#defs-code-heading").html("Definitions <div id='defs-hint' class='code-hint'>Press shift-enter to run</div>");
      this.hint = $("#defs-hint");
      this.hint.hide();
      this.resources = $blab.resources;
      this.coffee = this.resources.add({
        url: this.filename
      });
      $blab.definitions = {};
      $blab.use = (function(_this) {
        return function(id, callback) {
          if (id == null) {
            id = null;
          }
          return _this.use(id, callback);
        };
      })(this);
      this.allLoaded = false;
      $blab.defs = {};
      $blab.mainDefs = (function(_this) {
        return function(defs) {
          return _this.main(defs);
        };
      })(this);
      this.precode(this.filename);
      $(document).on("preCompileCoffee", (function(_this) {
        return function(evt, data) {
          var resource, url;
          resource = data.resource;
          url = resource.url;
          if (url !== _this.filename) {
            return;
          }
          $blab.defs = {};
          $blab.definitions = {};
          return _this.allLoaded = false;
        };
      })(this));
      this.resources.loadUnloaded((function(_this) {
        return function() {
          return _this.coffee.compile();
        };
      })(this));
    }

    Definitions.prototype.main = function(defs) {
      if (typeof defs === "string") {
        this.directDefs(defs);
        return;
      }
      $blab.definitions[this.filename] = defs;
      defs.loaded = true;
      $blab.defs = defs;
      this.checkLoaded(defs);
      return defs;
    };

    Definitions.prototype.directDefs = function(id) {
      var gist;
      gist = this.use(id);
      return this.main({
        derived: function() {
          var name, property, _results;
          _results = [];
          for (name in gist) {
            property = gist[name];
            if (!(name === "loaded" || name === "isImport")) {
              _results.push(this[name] = property);
            } else {
              _results.push(void 0);
            }
          }
          return _results;
        }
      });
    };

    Definitions.prototype.use = function(id, callback) {
      var defs, url, _base;
      if (id == null) {
        id = null;
      }
      url = (id ? "" + id + "/" : "") + this.filename;
      if ((_base = $blab.definitions)[url] == null) {
        _base[url] = {};
      }
      defs = $blab.definitions[url];
      if (defs.isImport == null) {
        defs.isImport = true;
      }
      if (defs.loaded == null) {
        defs.loaded = false;
      }
      if (defs.loaded) {
        setTimeout(((function(_this) {
          return function() {
            return _this.checkLoaded(defs);
          };
        })(this)), 0);
      } else {
        this.loadCoffee(url, (function(_this) {
          return function() {
            if (typeof callback === "function") {
              callback(defs);
            }
            return _this.getDefs(url, defs);
          };
        })(this));
      }
      return defs;
    };

    Definitions.prototype.getDefs = function(url, defs) {
      var blabDefs, def, name;
      blabDefs = $blab.definitions[url];
      blabDefs.loaded = true;
      for (name in blabDefs) {
        def = blabDefs[name];
        defs[name] = def;
      }
      return this.checkLoaded(defs);
    };

    Definitions.prototype.checkLoaded = function(defs) {
      var blabDefs, checkAll, def, name, url, _ref;
      if (this.allLoaded) {
        return;
      }
      if (!defs.loaded) {
        return false;
      }
      checkAll = true;
      for (name in defs) {
        def = defs[name];
        if (def.isImport && !def.loaded) {
          checkAll = false;
        }
      }
      if (!checkAll) {
        return false;
      }
      _ref = $blab.definitions;
      for (url in _ref) {
        blabDefs = _ref[url];
        if (!blabDefs.loaded) {
          return false;
        }
      }
      this.allDone();
      return true;
    };

    Definitions.prototype.allDone = function() {
      this.processDerived($blab.defs);
      this.allLoaded = true;
      if (this.firstDone != null) {
        return $.event.trigger("allBlabDefinitionsLoaded", {
          list: this.list()
        });
      } else {
        return this.done((function(_this) {
          return function() {
            _this.firstDone = true;
            return $.event.trigger("allBlabDefinitionsLoaded", {
              list: _this.list()
            });
          };
        })(this));
      }
    };

    Definitions.prototype.processDerived = function(d) {
      var def, name;
      for (name in d) {
        def = d[name];
        if (def.isImport) {
          this.processDerived(def);
        }
      }
      return typeof d.derived === "function" ? d.derived() : void 0;
    };

    Definitions.prototype.list = function() {
      var d, def, list, name, _ref;
      d = [];
      console.log("$blab.defs", $blab.defs);
      _ref = $blab.defs;
      for (name in _ref) {
        def = _ref[name];
        if (!(name === "loaded" || name === "derived")) {
          d.push(name);
        }
      }
      list = d.join(", ");
      return "{" + list + "} = $blab.defs";
    };

    Definitions.prototype.initEditor = function() {
      var _ref, _ref1;
      this.editor = (_ref = this.coffee.containers) != null ? (_ref1 = _ref.fileNodes) != null ? _ref1[0].editor : void 0 : void 0;
      this.aceEditor = this.editor.editor;
      this.aceEditor.on("focus", (function(_this) {
        return function() {
          return _this.hint.fadeIn();
        };
      })(this));
      return this.aceEditor.on("blur", (function(_this) {
        return function() {
          return _this.hint.fadeOut();
        };
      })(this));
    };

    Definitions.prototype.loadCoffee = function(url, callback) {
      var coffee, coffeeIdx, gistId, idx, match, r, rArray, re, _i, _len;
      rArray = this.resources.resources;
      for (idx = _i = 0, _len = rArray.length; _i < _len; idx = ++_i) {
        r = rArray[idx];
        if (r.url === url) {
          coffeeIdx = idx;
        }
      }
      if (coffeeIdx) {
        rArray.splice(coffeeIdx, 1);
      }
      if (url.indexOf("gist") === 0) {
        re = /^gist:([a-z0-9_-]+)/;
        match = re.exec(url);
        if (!match) {
          return;
        }
        gistId = match[1];
        this.gist(gistId, (function(_this) {
          return function(data) {
            var coffee, source;
            source = data.defs;
            coffee = _this.resources.add({
              url: url,
              source: source
            });
            coffee.gistData = data;
            coffee.location.inBlab = false;
            return _this.doLoad(coffee, callback);
          };
        })(this));
        return;
      }
      coffee = this.resources.add({
        url: url
      });
      return this.doLoad(coffee, callback);
    };

    Definitions.prototype.doLoad = function(coffee, callback) {
      var url;
      url = coffee.url;
      this.precode(url);
      return this.resources.load((function(resource) {
        return resource.url === url;
      }), (function(_this) {
        return function() {
          coffee.compile();
          return typeof callback === "function" ? callback() : void 0;
        };
      })(this));
    };

    Definitions.prototype.precode = function(url) {
      var preamble, precompile;
      preamble = "blabId = \"" + url + "\"\nuse = (id, callback) -> $blab.use(id, callback)\ndefs = (d) ->\n  if blabId is \"defs.coffee\"\n    return $blab.mainDefs(d)\n  else\n    $blab.definitions[blabId] = d\n    return d\n\n\n";
      precompile = {};
      precompile[url] = {
        preamble: preamble,
        postamble: ""
      };
      return $blab.precompile(precompile);
    };

    Definitions.prototype.gist = function(gistId, callback) {
      var api, url;
      api = "https://api.github.com/gists";
      url = "" + api + "/" + gistId;
      return $.get(url, (function(_this) {
        return function(data) {
          var defs, description, owner, _ref, _ref1, _ref2;
          defs = (_ref = (_ref1 = data.files) != null ? (_ref2 = _ref1["defs.coffee"]) != null ? _ref2.content : void 0 : void 0) != null ? _ref : null;
          description = data.description;
          owner = data.owner.login;
          return typeof callback === "function" ? callback({
            defs: defs,
            description: description,
            owner: owner
          }) : void 0;
        };
      })(this));
    };

    return Definitions;

  })();

  Buttons = (function() {
    function Buttons(spec) {
      var b, showCode, _ref, _ref1, _ref2, _ref3, _ref4, _ref5;
      this.spec = spec;
      this.container = $("#buttons");
      this.resources = $blab.resources;
      this.isGist = this.resources.getSource != null;
      this.isDemo = this.isGist && this.resources.getSource("demo.coffee");
      this.isStart = !this.isGist;
      this.isBlab = this.isGist && !this.isDemo;
      this.settings = spec.getSettings();
      showCode = function() {
        return $("#computation-code-wrapper").show();
      };
      if (((_ref = this.settings) != null ? _ref.showCodeOnLoad : void 0) || ((this.isStart || this.isDemo) && (((_ref1 = this.settings) != null ? _ref1.showCodeOnLoad : void 0) == null))) {
        showCode();
      }
      if (this.isStart) {
        if ((_ref2 = this.settings) != null ? _ref2.showCodeOnLoad : void 0) {
          showCode();
        }
        this.startButtons();
      }
      if (this.isBlab) {
        $("#top-banner").slideUp();
        if ((_ref3 = this.settings) != null ? _ref3.showCodeOnLoad : void 0) {
          showCode();
        }
        this.append("<hr>");
        this.logo();
        this.docButton();
        this.sep();
        this.sourceButton();
        this.sep();
        this.revisionsButton();
        this.sep();
        this.showForkButton();
        this.sep();
        this.commentsButton();
        this.sep();
        b = this.linkButton("Edit Page", (function(_this) {
          return function() {
            return _this.makeEditable();
          };
        })(this));
        b.css({
          color: "green",
          fontWeight: "bold",
          textDecoration: "none"
        });
        b.attr({
          title: "Edit blab's layout, text, and widgets."
        });
        if ((_ref4 = this.settings) != null ? _ref4.showAuthor : void 0) {
          this.author();
        }
      }
      if (this.isDemo) {
        $("#top-banner").slideUp();
        if ((this.settings == null) || ((_ref5 = this.settings) != null ? _ref5.showCodeOnLoad : void 0) === true) {
          showCode();
        }
        this.makeEditable();
      }
    }

    Buttons.prototype.logo = function() {
      var logo, logoDiv;
      logoDiv = $("<div>", {
        id: "blabr-logo-footer",
        click: (function(_this) {
          return function() {
            return _this.spec.guide();
          };
        })(this)
      });
      logo = $("<img>", {
        src: "img/blabr-logo.png"
      });
      logoDiv.append(logo).append("Blabr");
      return this.append(logoDiv);
    };

    Buttons.prototype.startButtons = function() {
      this.container.empty();
      this.append("<hr>");
      this.logo();
      return this.docButton();
    };

    Buttons.prototype.makeEditable = function() {
      if (this.isStart) {
        return;
      }
      $("#computation-code-wrapper").show(500);
      this.spec.makeEditable();
      this.startButtons();
      this.appendBlabButtons();
      return this.author();
    };

    Buttons.prototype.appendBlabButtons = function() {
      var s;
      this.sep();
      this.sourceButton();
      this.sep();
      this.revisionsButton();
      this.sep();
      this.showForkButton();
      this.sep();
      this.commentsButton();
      this.sep();
      s = this.linkButton("Settings", (function(_this) {
        return function() {
          console.log("settings");
          return _this.spec.editSettings();
        };
      })(this));
      return s.attr({
        title: "Edit blab settings."
      });
    };

    Buttons.prototype.docButton = function() {
      return this.linkButton("Doc & Examples", (function(_this) {
        return function() {
          return _this.spec.guide();
        };
      })(this));
    };

    Buttons.prototype.sourceButton = function() {
      var l, _ref;
      l = this.linkButton("Source Control", (function() {}), (_ref = $blab.github) != null ? _ref.sourceLink() : void 0);
      return l.attr({
        title: "View GitHub Gist page for this blab."
      });
    };

    Buttons.prototype.revisionsButton = function() {
      var l, _ref;
      l = this.linkButton("Revisions", (function() {}), ((_ref = $blab.github) != null ? _ref.sourceLink() : void 0) + "/revisions");
      return l.attr({
        title: "View GitHub Gist revisions for this blab."
      });
    };

    Buttons.prototype.commentsButton = function() {
      var l, _ref;
      l = this.linkButton("Comment", (function() {}), ((_ref = $blab.github) != null ? _ref.sourceLink() : void 0) + "#comments");
      return l.attr({
        title: "Comment on this blab in GitHub Gist page."
      });
    };

    Buttons.prototype.showForkButton = function() {
      var b;
      b = this.forkButton = this.linkButton("Fork", (function(_this) {
        return function() {
          var forceNew, _ref;
          forceNew = true;
          return (_ref = $blab.github) != null ? _ref.save(forceNew) : void 0;
        };
      })(this));
      return b.attr({
        title: "Create your own version of this blab."
      });
    };

    Buttons.prototype.author = function() {
      var a, author, owner, _ref, _ref1;
      owner = (_ref = $blab.github) != null ? (_ref1 = _ref.gist) != null ? _ref1.gistOwner : void 0 : void 0;
      if (!owner) {
        return;
      }
      author = $("<div>", {
        id: "blab-author",
        text: "Author: ",
        css: {
          float: "right"
        }
      });
      a = $("<a>", {
        text: "@" + owner,
        href: "//gist.github.com/" + owner,
        target: "_blank",
        css: {
          textDecoration: "none"
        }
      });
      author.append(a);
      return this.container.append(author);
    };

    Buttons.prototype.createButton = function(txt) {
      var button;
      button = $("<button>", {
        text: txt
      });
      this.append(button);
      return button;
    };

    Buttons.prototype.linkButton = function(txt, click, href) {
      var button;
      button = $("<a>", {
        click: function() {
          return typeof click === "function" ? click() : void 0;
        },
        text: txt,
        target: "_blank"
      });
      if (href) {
        button.attr({
          href: href
        });
      }
      this.append(button);
      return button;
    };

    Buttons.prototype.append = function(element) {
      return this.container.append(element);
    };

    Buttons.prototype.sep = function() {
      return this.append(" | ");
    };

    return Buttons;

  })();

  EditPageButton = (function() {
    function EditPageButton(container, callback) {
      this.container = container;
      this.callback = callback;
      this.div = $("<div>", {
        id: "edit-page-button-container",
        css: {
          position: "fixed",
          bottom: 20,
          right: 10,
          zIndex: 300
        }
      });
      this.b = $("<a>", {
        id: "edit-page-button",
        click: (function(_this) {
          return function() {
            _this.b.button("refresh");
            return typeof _this.callback === "function" ? _this.callback() : void 0;
          };
        })(this)
      });
      this.b.button({
        label: "Layout"
      });
      this.div.append(this.b);
      this.container.append(this.div);
      this.hide();
    }

    EditPageButton.prototype.show = function() {
      return this.b.show();
    };

    EditPageButton.prototype.hide = function() {
      return this.b.hide();
    };

    return EditPageButton;

  })();

  Errors = (function() {
    Errors.prototype.errors = {
      "compute.coffee": {
        heading: "Computation",
        error: null
      },
      "defs.coffee": {
        heading: "Definitions",
        error: null
      },
      "layout.coffee": {
        heading: "Layout",
        error: null
      }
    };

    Errors.prototype.containerSel = "#blab-error";

    Errors.prototype.enable = true;

    function Errors() {
      var name;
      this.container = $(this.containerSel);
      this.filenames = (function() {
        var _results;
        _results = [];
        for (name in this.errors) {
          _results.push(name);
        }
        return _results;
      }).call(this);
      window.onerror = (function(_this) {
        return function(e, url, line) {
          return $blab.windowError = e;
        };
      })(this);
      $(document).on("preCompileCoffee", (function(_this) {
        return function(e, data) {
          return _this.reset(data.resource.url);
        };
      })(this));
      $(document).on("blabError", (function(_this) {
        return function(evt, data) {
          var filename;
          filename = data.source;
          if (!(_this.enable && __indexOf.call(_this.filenames, filename) >= 0)) {
            return;
          }
          $blab.windowError = false;
          _this.set(filename, data.error);
          return _this.disp();
        };
      })(this));
    }

    Errors.prototype.reset = function(filename) {
      var e, name, _ref, _results;
      _ref = this.errors;
      _results = [];
      for (name in _ref) {
        e = _ref[name];
        if (filename === name) {
          _results.push(this.errors[name].error = null);
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    Errors.prototype.set = function(filename, error) {
      var e, name, _ref, _results;
      _ref = this.errors;
      _results = [];
      for (name in _ref) {
        e = _ref[name];
        if (filename === name) {
          _results.push(this.errors[name].error = error ? error : null);
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    Errors.prototype.disp = function() {
      var e, error, first, name, show, str, _ref;
      this.container.empty();
      new $blab.utils.CloseButton(this.container, (function(_this) {
        return function() {
          return _this.container.hide();
        };
      })(this));
      first = true;
      show = false;
      str = "";
      _ref = this.errors;
      for (name in _ref) {
        e = _ref[name];
        error = e.error;
        if (!error) {
          continue;
        }
        show = true;
        if (!first) {
          str += "<br><br>";
        }
        str += ("<b>" + e.heading + "</b><br>") + error;
        first = false;
      }
      this.container.append(str);
      if (show) {
        return this.container.show();
      } else {
        return this.container.hide();
      }
    };

    return Errors;

  })();

  Loader = (function() {
    function Loader(init) {
      var done, hasDemo, layout, tables;
      this.init = init;
      this.resources = $blab.resources;
      this.resources.blockPostLoadFromSpecFile = true;
      layout = this.resources.add({
        url: "layout.coffee"
      });
      tables = this.resources.add({
        url: "tables.json"
      });
      hasDemo = (this.resources.getSource == null) || this.resources.getSource("demo.coffee");
      done = (function(_this) {
        return function(cb) {
          _this.resources.postLoadFromSpecFile();
          return cb();
        };
      })(this);
      this.resources.loadUnloaded((function(_this) {
        return function() {
          return _this.definitions = new Definitions(function(cb) {
            var demo;
            _this.init();
            layout.compile();
            $blab.blabrGuide = new $blab.guideClass;
            if (hasDemo) {
              demo = _this.resources.add({
                url: "demo.coffee"
              });
              _this.resources.add({
                url: "js/demo-runner.js"
              });
              return _this.resources.loadUnloaded(function() {
                if (demo != null) {
                  demo.compile();
                }
                return done(cb);
              });
            } else {
              return done(cb);
            }
          });
        };
      })(this));
    }

    return Loader;

  })();

  BlabEvents = (function() {
    function BlabEvents() {
      this.body = $(document.body);
      this.body.mousedown((function(_this) {
        return function(e) {
          return _this.trigger("blabmousedown");
        };
      })(this));
      this.body.mouseup((function(_this) {
        return function(e) {
          return _this.trigger("blabmouseup");
        };
      })(this));
      document.body.addEventListener("copy", (function(_this) {
        return function(e) {
          return _this.trigger("blabcopy", {
            original: e
          });
        };
      })(this));
      this.unbind(["blabcompute"]);
      this.on("preCompileCoffee", (function(_this) {
        return function(e, data) {
          return _this.unbinds(data.resource.url);
        };
      })(this));
      this.on("compiledCoffeeScript", (function(_this) {
        return function(e, data) {
          return _this.triggers(data.url);
        };
      })(this));
    }

    BlabEvents.prototype.unbinds = function(filename) {
      if (filename === "layout.coffee") {
        this.unbind(["blabcompute"]);
      }
      return this.unbind(["blabmousedown", "blabmouseup", "blabcopy", "blabpaste"]);
    };

    BlabEvents.prototype.triggers = function(filename) {
      var isCompute, isLayout;
      isCompute = filename === "compute.coffee";
      isLayout = filename === "layout.coffee";
      if (!(isCompute || isLayout)) {
        this.trigger("blabError", {
          source: filename,
          error: $blab.windowError
        });
      }
      if (isCompute) {
        return this.trigger("blabcompute");
      }
    };

    BlabEvents.prototype.on = function(name, handler) {
      return $(document).on(name, function(evt, data) {
        return handler(evt, data);
      });
    };

    BlabEvents.prototype.trigger = function(evt, data) {
      return $.event.trigger(evt, data);
    };

    BlabEvents.prototype.unbind = function(events) {
      var e, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = events.length; _i < _len; _i++) {
        e = events[_i];
        _results.push($(document).unbind(e));
      }
      return _results;
    };

    return BlabEvents;

  })();

  Background = (function() {
    function Background(background) {
      if (background) {
        $(document.body).css({
          backgroundImage: "url(" + background + ")"
        });
        $("#outer-container").addClass("outer-background");
        $("#outer-container").css({
          marginTop: 30,
          paddingTop: 10
        });
        $("#container").css({
          marginTop: 20
        });
      } else {
        $(document.body).css({
          backgroundImage: ""
        });
        $("#outer-container").removeClass("outer-background");
        $("#outer-container").css({
          marginTop: 0,
          paddingTop: 0
        });
        $("#container").css({
          marginTop: 40
        });
      }
    }

    return Background;

  })();

  Settings = (function() {
    function Settings() {}

    Settings.prototype.set = function(spec) {
      var author, _ref, _ref1, _ref2, _ref3;
      this.spec = spec;
      new Background((_ref = this.spec) != null ? _ref.background : void 0);
      author = $("#blab-author");
      this.spec.showAuthor = (((_ref1 = this.spec) != null ? _ref1.showAuthor : void 0) == null) || ((_ref2 = this.spec) != null ? _ref2.showAuthor : void 0);
      if (author.length) {
        if ((_ref3 = this.spec) != null ? _ref3.showAuthor : void 0) {
          return author.show();
        } else {
          return author.hide();
        }
      }
    };

    return Settings;

  })();

  PopupEditorManager = (function() {
    function PopupEditorManager(spec) {
      var _ref;
      this.spec = spec;
      this.highlightWidget = __bind(this.highlightWidget, this);
      _ref = this.spec, this.widgetEditor = _ref.widgetEditor, this.markdownEditor = _ref.markdownEditor;
      this.layoutEnabled = false;
      this.clickedOnComponent = false;
      this.currentComponent = null;
      this.markdownEditor.on("clickText", (function(_this) {
        return function(data) {
          var _ref1;
          if (((_ref1 = data.evt) != null ? _ref1.target.tagName : void 0) === "A") {
            data.evt.stopPropagation();
            return;
          }
          return _this.showMarkdownEditor(data.start);
        };
      })(this));
      this.markdownEditor.on("setViewPort", (function(_this) {
        return function() {
          return _this.highlightLayout();
        };
      })(this));
      this.markdownEditor.on("clickCloseButton", (function(_this) {
        return function() {
          return _this.disableLayout();
        };
      })(this));
      this.widgetEditor.on("setViewPort", (function(_this) {
        return function() {
          return _this.highlightLayout();
        };
      })(this));
      this.widgetEditor.on("clickCloseButton", (function(_this) {
        return function() {
          return _this.disableLayout();
        };
      })(this));
      this.widgetEditor.on("clickDelete", (function(_this) {
        return function() {
          return _this.clickedOnComponent = true;
        };
      })(this));
      this.on("clickWidget", (function(_this) {
        return function(evt, data) {
          return _this.showLayoutEditor({
            widget: data.widget
          });
        };
      })(this));
      Layout.on("clickBox", (function(_this) {
        return function(data) {
          if (data.evt.target.className === "editable-table-cell") {
            return;
          }
          return _this.showLayoutEditor({
            signature: "layout"
          });
        };
      })(this));
      $(document.body).click((function(_this) {
        return function(evt) {
          return _this.hideAll(evt);
        };
      })(this));
      this.on("clickInputWidget", (function(_this) {
        return function(evt, data) {
          return _this.hideLayout();
        };
      })(this));
      this.editPageButton = new EditPageButton($("#edit-page"), (function(_this) {
        return function() {
          return _this.enableLayout();
        };
      })(this));
    }

    PopupEditorManager.prototype.enableLayout = function() {
      this.enable();
      return this.showLayoutEditor({
        signature: "layout",
        clicked: true
      });
    };

    PopupEditorManager.prototype.disableLayout = function() {
      this.enable(false);
      return this.hideLayout();
    };

    PopupEditorManager.prototype.enable = function(enabled) {
      if (enabled == null) {
        enabled = true;
      }
      if (enabled) {
        this.initEnabled = true;
      }
      return this.layoutEnabled = enabled;
    };

    PopupEditorManager.prototype.cursorOnWidget = function(widget) {
      return this.showLayoutEditor({
        widget: widget,
        id: null,
        clicked: false
      });
    };

    PopupEditorManager.prototype.showMarkdownEditor = function(start) {
      console.log("showMarkdownEditor", this.layoutEnabled);
      if (!this.layoutEnabled) {
        return;
      }
      this.clickedOnComponent = true;
      setTimeout(((function(_this) {
        return function() {
          return _this.clickedOnComponent = false;
        };
      })(this)), 300);
      this.highlightWidget(null);
      this.widgetEditor.setViewPort(null);
      return this.markdownEditor.setViewPort(start);
    };

    PopupEditorManager.prototype.showLayoutEditor = function(spec) {
      var clicked, id, signature, type, widget, _ref, _ref1, _ref2;
      if (!this.layoutEnabled) {
        return;
      }
      if (this.clickedOnComponent) {
        return;
      }
      widget = spec.widget;
      signature = (_ref = spec.signature) != null ? _ref : null;
      clicked = (_ref1 = spec.clicked) != null ? _ref1 : true;
      if (widget) {
        type = widget.constructor.handle;
        id = widget.id;
        signature = type + " " + ("\"" + id + "\"");
      }
      if (clicked) {
        this.clickedOnComponent = true;
        setTimeout(((function(_this) {
          return function() {
            return _this.clickedOnComponent = false;
          };
        })(this)), 300);
      }
      this.widgetEditor.setViewPort(signature);
      this.markdownEditor.setViewPort(null);
      this.highlightWidget((_ref2 = widget != null ? widget.mainContainer : void 0) != null ? _ref2 : null);
      if (widget) {
        this.widgetEditor.currentId = widget.domId();
      }
      if (signature) {
        return this.editPageButton.hide();
      }
    };

    PopupEditorManager.prototype.highlightLayout = function() {
      var displayed;
      displayed = this.widgetEditor.viewPortDisplayed || this.markdownEditor.viewPortDisplayed;
      Layout.highlight(displayed);
      if (displayed) {
        return this.editPageButton.hide();
      }
    };

    PopupEditorManager.prototype.hideLayout = function() {
      this.highlightWidget(null);
      this.widgetEditor.setViewPort(null);
      this.markdownEditor.setViewPort(null);
      if (this.layoutEnabled) {
        return this.editPageButton.hide();
      } else {
        if (this.initEnabled) {
          return setTimeout(((function(_this) {
            return function() {
              return _this.editPageButton.b.fadeIn(500);
            };
          })(this)), 500);
        }
      }
    };

    PopupEditorManager.prototype.highlightWidget = function(component) {
      var _ref, _ref1;
      if ((_ref = this.currentComponent) != null) {
        _ref.removeClass("widget-highlight");
      }
      this.currentComponent = component;
      return (_ref1 = this.currentComponent) != null ? _ref1.addClass("widget-highlight") : void 0;
    };

    PopupEditorManager.prototype.hideAll = function(evt) {
      return setTimeout(((function(_this) {
        return function() {
          if (!(_this.clickedOnComponent || $(evt.target).attr("class"))) {
            _this.hideLayout();
          }
          return _this.clickedOnComponent = false;
        };
      })(this)), 100);
    };

    PopupEditorManager.prototype.on = function(name, handler) {
      return $(document).on(name, function(evt, data) {
        return handler(evt, data);
      });
    };

    return PopupEditorManager;

  })();

  GoogleAnalytics = (function() {
    function GoogleAnalytics() {
      var title;
      this.codeChanged = false;
      title = function() {
        var id, _ref, _ref1;
        id = (_ref = $blab.github) != null ? (_ref1 = _ref.gist) != null ? _ref1.id : void 0 : void 0;
        title = $blab.title === "Untitled" && !id ? "---Home Page---" : $blab.title;
        if (id) {
          return "" + title + " [" + id + "]";
        } else {
          return title;
        }
      };
      this.track("blabEditorsInitialized", "blab", "view", title);
      this.track("codeNodeChanged", "blab", "firstEdit", title, ((function(_this) {
        return function() {
          return !_this.codeChanged;
        };
      })(this)), ((function(_this) {
        return function() {
          return _this.codeChanged = true;
        };
      })(this)));
      this.track("saveGitHub", "blab", "saveButton", title);
      this.track("createBlab", "blab", "createBlab", title);
      this.track("forkBlab", "blab", "forkBlab", title);
      this.track("runBlabDemo", "blab", "runDemo", title);
    }

    GoogleAnalytics.prototype.track = function(blabEvent, gCat, gEvent, gTextFcn, condition, callback) {
      if (condition == null) {
        condition = (function() {
          return true;
        });
      }
      return $(document).on(blabEvent, (function(_this) {
        return function() {
          var gText;
          gText = gTextFcn();
          if (condition()) {
            if (typeof _gaq !== "undefined" && _gaq !== null) {
              _gaq.push(["_trackEvent", gCat, gEvent, gText]);
            }
          }
          return typeof callback === "function" ? callback() : void 0;
        };
      })(this));
    };

    return GoogleAnalytics;

  })();

  App = (function() {
    function App() {
      new GoogleAnalytics;
      this.loader = new Loader((function(_this) {
        return function() {
          return _this.init();
        };
      })(this));
    }

    App.prototype.init = function() {
      new BlabEvents;
      Widgets.initialize();
      this.widgetEditor = Widgets.widgetEditor;
      this.computationEditor = new ComputationEditor;
      this.markdownEditor = new MarkdownEditor;
      this.definitions = this.loader.definitions;
      this.on("aceFilesLoaded", (function(_this) {
        return function() {
          return _this.initEditors();
        };
      })(this));
      this.beforeCompute((function(_this) {
        return function() {
          Computation.precode();
          return Widgets.setAllUnused();
        };
      })(this));
      Layout.on("renderedWidgets", (function(_this) {
        return function() {
          return _this.markdownEditor.setWidgetsRendered();
        };
      })(this));
      $("#computation-code-wrapper").hide();
      this.on("layoutCompiled", (function(_this) {
        return function() {
          return _this.initButtons();
        };
      })(this));
      this.on("codeNodeChanged", (function(_this) {
        return function() {
          if (_this.changed) {
            return;
          }
          _this.changed = true;
          return _this.buttons.makeEditable();
        };
      })(this));
      this.settingsObj = new Settings;
      this.errors = new Errors;
      return $pz.renderHtml = (function(_this) {
        return function() {
          return _this.markdownEditor.process();
        };
      })(this);
    };

    App.prototype.initEditors = function() {
      this.markdownEditor.process();
      this.definitions.initEditor();
      this.editors = new PopupEditorManager({
        widgetEditor: this.widgetEditor,
        markdownEditor: this.markdownEditor
      });
      this.computationEditor.on("cursorOnWidget", (function(_this) {
        return function(data) {
          var _ref, _ref1;
          if (((((_ref = _this.settings) != null ? _ref.popupWidgetEditor : void 0) != null) && !((_ref1 = _this.settings) != null ? _ref1.popupWidgetEditor : void 0)) || _this.disablePopupWidgetEditor) {
            return;
          }
          return _this.editors.cursorOnWidget(data.widget);
        };
      })(this));
      setTimeout(((function(_this) {
        return function() {
          return _this.computationEditor.initFocusBlur();
        };
      })(this)), 900);
      this.markdownEditor.on("initialized", (function(_this) {
        return function() {
          return $.event.trigger("blabEditorsInitialized");
        };
      })(this));
      if ($blab.resources.getSource == null) {
        return this.editors.enable();
      }
    };

    App.prototype.initButtons = function() {
      if (this.buttons) {
        return;
      }
      return this.buttons = new Buttons({
        guide: (function(_this) {
          return function() {
            return $blab.blabrGuide.slideToggle();
          };
        })(this),
        makeEditable: (function(_this) {
          return function() {
            var _ref;
            return (_ref = _this.editors) != null ? _ref.enable() : void 0;
          };
        })(this),
        editSettings: (function(_this) {
          return function() {
            var _ref, _ref1;
            if ((_ref = _this.editors) != null) {
              _ref.enable();
            }
            return (_ref1 = _this.editors) != null ? _ref1.showLayoutEditor({
              signature: "settings"
            }) : void 0;
          };
        })(this),
        getSettings: (function(_this) {
          return function() {
            return _this.settings;
          };
        })(this)
      });
    };

    App.prototype.setSettings = function(settings) {
      this.settings = settings;
      return this.settingsObj.set(this.settings);
    };

    App.prototype.beforeCompute = function(handler) {
      return this.on("preCompileCoffee", (function(_this) {
        return function(e, data) {
          if (data.resource.url !== "compute.coffee") {
            return;
          }
          return handler();
        };
      })(this));
    };

    App.prototype.forceEditorRendering = function() {
      return setTimeout(((function(_this) {
        return function() {
          var _ref;
          if ((_ref = _this.computationEditor.aceEditor) != null) {
            _ref.focus();
          }
          return setTimeout((function() {
            var _ref1;
            if ((_ref1 = _this.computationEditor.aceEditor) != null) {
              _ref1.blur();
            }
            _this.definitions.aceEditor.focus();
            return setTimeout((function() {
              _this.definitions.aceEditor.blur();
              return _this.computationEditor.initFocusBlur();
            }), 300);
          }), 300);
        };
      })(this)), 300);
    };

    App.prototype.on = function(name, handler) {
      return $(document).on(name, function(evt, data) {
        return handler(evt, data);
      });
    };

    return App;

  })();

  $blab.AppClass = App;

  $blab.Layout = Layout;

  $blab.Widget = Widget;

  $blab.Widgets = Widgets;

  codeSections = function() {
    var comp, layout, predef, ps, removeInit, title, toggleHeading;
    title = "Show/hide code";
    comp = $("#computation-code-section");
    layout = $("#layout-code-section");
    predef = $(".predefined-code");
    predef.hide();
    $("#computation-code-heading").click(function() {
      return comp.toggle(500);
    });
    $("#layout-code-heading").click(function() {
      return layout.toggle(500);
    });
    ps = true;
    toggleHeading = function() {
      return ps = !ps;
    };
    toggleHeading();
    removeInit = function() {
      var editor, ev, resource, _ref, _ref1, _ref2, _ref3;
      resource = $blab.resources.find("predefine.coffee");
      editor = resource != null ? (_ref = resource.containers) != null ? (_ref1 = _ref.fileNodes) != null ? _ref1[0].editor : void 0 : void 0 : void 0;
      if (editor != null) {
        editor.container.removeClass("init-editor");
      }
      ev = resource != null ? (_ref2 = resource.containers) != null ? (_ref3 = _ref2.evalNodes) != null ? _ref3[0].editor : void 0 : void 0 : void 0;
      return ev != null ? ev.container.removeClass("init-editor") : void 0;
    };
    return $("#predefined-code-heading").click(function() {
      removeInit();
      predef.toggle(500);
      return toggleHeading();
    });
  };

  TextEditor = (function() {
    TextEditor.prototype.containerId = "#main-text";

    TextEditor.prototype.filename = "text.html";

    TextEditor.prototype.wikyUrl = "/puzlet/puzlet/js/wiky.js";

    TextEditor.prototype.posAttr = "data-pos";

    TextEditor.prototype.widgetsId = "#widgets-container";

    function TextEditor() {
      this.text = $(this.containerId);
      if (!this.text.length) {
        return;
      }
      this.text.css({
        cursor: "default"
      });
      this.text.click((function(_this) {
        return function() {
          return _this.toggle();
        };
      })(this));
      this.resources = $blab.resources;
      this.widgetsRendered = false;
    }

    TextEditor.prototype.setWidgetsRendered = function() {
      this.widgetsRendered = true;
      if (typeof Wiky !== "undefined" && Wiky !== null) {
        return this.process();
      }
    };

    TextEditor.prototype.loadWiky = function(callback) {
      console.log("TextEditor::loadWiky");
      this.resources.add({
        url: this.wikyUrl
      });
      return this.resources.loadUnloaded(function() {
        return typeof callback === "function" ? callback() : void 0;
      });
    };

    TextEditor.prototype.init = function() {
      var _ref, _ref1, _ref2;
      console.log("TextEditor::init");
      this.resource = this.resources.find(this.filename);
      this.editor = (_ref = this.resource) != null ? (_ref1 = _ref.containers) != null ? (_ref2 = _ref1.fileNodes) != null ? _ref2[0].editor : void 0 : void 0 : void 0;
      if (!this.editor) {
        return;
      }
      this.editor.container.removeClass("init-editor");
      this.editor.onChange((function(_this) {
        return function() {
          return _this.render();
        };
      })(this));
      this.editor.show(false);
      if (this.widgetsRendered) {
        return this.process();
      }
    };

    TextEditor.prototype.render = function() {
      if (this.renderId == null) {
        this.renderId = null;
      }
      if (this.renderId) {
        clearTimeout(this.renderId);
      }
      return this.renderId = setTimeout(((function(_this) {
        return function() {
          return _this.process();
        };
      })(this)), 500);
    };

    TextEditor.prototype.process = function() {
      var html;
      console.log("TextEditor::process");
      if (typeof Wiky === "undefined" || Wiky === null) {
        this.loadWiky((function(_this) {
          return function() {
            return _this.init();
          };
        })(this));
        return;
      }
      console.log("TextEditor::process/Wiky");
      this.text.empty();
      html = Wiky.toHtml(this.resource.content);
      if (html === "") {
        return;
      }
      this.text.append(html);
      this.setTitle();
      this.positionText();
      return $.event.trigger("htmlOutputUpdated");
    };

    TextEditor.prototype.setTitle = function() {
      var headings;
      headings = $(":header");
      if (!headings.length) {
        return;
      }
      $blab.title = headings[0].innerHTML;
      return document.title = $blab.title;
    };

    TextEditor.prototype.positionText = function() {
      var append, current, divs, sel, widgets;
      sel = "div[" + this.posAttr + "]";
      widgets = $(this.widgetsId);
      current = widgets.find(sel);
      current.remove();
      divs = this.text.find(sel);
      if (!divs.length) {
        return;
      }
      append = (function(_this) {
        return function() {
          var p, _i, _len, _results;
          _results = [];
          for (_i = 0, _len = divs.length; _i < _len; _i++) {
            p = divs[_i];
            _results.push($($(p).attr(_this.posAttr)).append($(p)));
          }
          return _results;
        };
      })(this);
      if (widgets.length) {
        return append();
      } else {
        return setTimeout((function() {
          return append();
        }), 1000);
      }
    };

    TextEditor.prototype.toggle = function() {
      if (!this.editor) {
        return;
      }
      if (this.editorShown == null) {
        this.editorShown = false;
      }
      this.editor.show(!this.editorShown);
      return this.editorShown = !this.editorShown;
    };

    return TextEditor;

  })();

}).call(this);
