// Generated by CoffeeScript 1.7.1
(function() {
  var AxesLabels, EditableCell, Input, Plot, Slider, Table, TableCellSelector, Widget,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Widget = $blab.Widget;

  Input = (function(_super) {
    __extends(Input, _super);

    function Input() {
      return Input.__super__.constructor.apply(this, arguments);
    }

    Input.handle = "input";

    Input.initVal = 0;

    Input.initSpec = function(id) {
      return "init: " + Input.initVal + "\nprompt: \"" + id + ":\"\nunit: \"\"\nalign: \"left\"\npos: 1, order: 1";
    };

    Input.compute = function() {
      var id, v, _ref;
      id = arguments[0], v = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return (_ref = this.getVal.apply(this, [id].concat(__slice.call(v)))) != null ? _ref : this.initVal;
    };

    Input.prototype.create = function(spec) {
      var clickEvent, _ref, _ref1;
      this.spec = spec;
      _ref = this.spec, this.init = _ref.init, this.prompt = _ref.prompt, this.unit = _ref.unit, this.align = _ref.align;
      this.inputContainer = $("#" + this.domId());
      if (this.inputContainer.length) {
        this.outer = this.inputContainer.parent();
        if ((_ref1 = this.outer) != null) {
          _ref1.remove();
        }
      }
      clickEvent = (function(_this) {
        return function() {
          return _this.select();
        };
      })(this);
      this.outer = $("<div>", {
        "class": "input-container"
      });
      this.promptContainer = $("<div>", {
        "class": "input-prompt-container"
      });
      this.outer.append(this.promptContainer);
      this.inputPrompt = $("<div>", {
        "class": "input-prompt"
      });
      this.promptContainer.append(this.inputPrompt);
      this.inputPrompt.append(this.prompt);
      this.inputContainer = $("<div>", {
        "class": "blab-input",
        id: this.domId(),
        mouseup: (function(_this) {
          return function(e) {
            return e.stopPropagation();
          };
        })(this)
      });
      this.outer.append(this.inputContainer);
      this.outer.mouseup(function() {
        return clickEvent();
      });
      this.textContainer = $("<div>", {
        "class": "input-text-container"
      });
      this.outer.append(this.textContainer);
      this.textDiv = $("<div>", {
        "class": "input-text"
      });
      this.textContainer.append(this.textDiv);
      if (this.unit) {
        this.textDiv.html(this.unit);
      }
      this.appendToCanvas(this.outer);
      this.input = $("<input>", {
        type: "number",
        value: this.init,
        mouseup: function(e) {
          return e.stopPropagation();
        },
        change: (function(_this) {
          return function() {
            _this.setVal(parseFloat(_this.input.val()));
            return _this.computeAll();
          };
        })(this)
      });
      if (this.align) {
        this.input.css({
          textAlign: this.align
        });
      }
      this.inputContainer.append(this.input);
      return this.setVal(this.init);
    };

    Input.prototype.initialize = function() {
      return this.setVal(this.init);
    };

    Input.prototype.setVal = function(v) {
      return this.value = v;
    };

    Input.prototype.getVal = function() {
      this.setUsed();
      return this.value;
    };

    return Input;

  })(Widget);

  Slider = (function(_super) {
    __extends(Slider, _super);

    function Slider() {
      return Slider.__super__.constructor.apply(this, arguments);
    }

    Slider.handle = "slider";

    Slider.initVal = 5;

    Slider.initSpec = function(id) {
      return "min: 0, max: 10, step: 0.1, init: " + Slider.initVal + "\nprompt: \"" + id + ":\"\nunit: \"\"\npos: 1, order: 1";
    };

    Slider.compute = function() {
      var id, v, _ref;
      id = arguments[0], v = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return (_ref = this.getVal.apply(this, [id].concat(__slice.call(v)))) != null ? _ref : this.initVal;
    };

    Slider.prototype.create = function(spec) {
      var clickEvent, sliding, _base, _ref, _ref1, _ref2;
      this.spec = spec;
      _ref = this.spec, this.min = _ref.min, this.max = _ref.max, this.step = _ref.step, this.init = _ref.init, this.prompt = _ref.prompt, this.text = _ref.text, this.val = _ref.val, this.unit = _ref.unit;
      this.sliderContainer = $("#" + this.domId());
      if (this.sliderContainer.length) {
        if (typeof (_base = this.sliderContainer).slider === "function") {
          _base.slider("destroy");
        }
        this.outer = this.sliderContainer.parent();
        if ((_ref1 = this.outer) != null) {
          _ref1.remove();
        }
      }
      sliding = false;
      clickEvent = (function(_this) {
        return function() {
          if (!sliding) {
            _this.select();
          }
          return sliding = false;
        };
      })(this);
      this.outer = $("<div>", {
        "class": "slider-container"
      });
      this.sliderPromptContainer = $("<div>", {
        "class": "slider-prompt-container"
      });
      this.outer.append(this.sliderPromptContainer);
      this.sliderPrompt = $("<div>", {
        "class": "slider-prompt"
      });
      this.sliderPromptContainer.append(this.sliderPrompt);
      this.sliderPrompt.append(this.prompt);
      this.sliderContainer = $("<div>", {
        "class": "puzlet-slider",
        id: this.domId(),
        mousedown: (function(_this) {
          return function(e) {
            return $.event.trigger("clickInputWidget");
          };
        })(this),
        mouseup: (function(_this) {
          return function(e) {
            return e.stopPropagation();
          };
        })(this)
      });
      this.outer.append(this.sliderContainer);
      this.outer.mouseup(function() {
        return clickEvent();
      });
      this.textContainer = $("<div>", {
        "class": "slider-text-container"
      });
      this.outer.append(this.textContainer);
      this.textDiv = $("<div>", {
        "class": "slider-text-1"
      });
      this.textContainer.append(this.textDiv);
      this.textDiv2 = $("<div>", {
        "class": "slider-text-2"
      });
      this.textContainer.append(this.textDiv2);
      if (this.unit) {
        this.textDiv2.html(this.unit);
      }
      this.appendToCanvas(this.outer);
      this.fast = (_ref2 = this.spec.fast) != null ? _ref2 : true;
      this.slider = this.sliderContainer.slider({
        range: "min",
        min: this.min,
        max: this.max,
        step: this.step,
        value: this.init,
        mouseup: function(e) {},
        slide: (function(_this) {
          return function(e, ui) {
            sliding = true;
            _this.setVal(ui.value);
            if (_this.fast) {
              return _this.computeAll();
            }
          };
        })(this),
        change: (function(_this) {
          return function(e, ui) {
            if (!_this.fast) {
              _this.computeAll();
            }
            return setTimeout((function() {
              return sliding = false;
            }), 100);
          };
        })(this)
      });
      return this.setVal(this.init);
    };

    Slider.prototype.initialize = function() {
      return this.setVal(this.init);
    };

    Slider.prototype.setVal = function(v) {
      this.textDiv.html(this.val ? this.val(v) : this.text ? this.text(v) : v);
      return this.value = v;
    };

    Slider.prototype.getVal = function() {
      this.setUsed();
      return this.value;
    };

    return Slider;

  })(Widget);

  Table = (function(_super) {
    __extends(Table, _super);

    function Table() {
      return Table.__super__.constructor.apply(this, arguments);
    }

    Table.handle = "table";

    Table.initSpec = function(id, v) {
      return "title: \"" + id + "\"\nheadings: []  # [\"Column 1\", \"Column 2\"]\nwidths: 100  #[100, 100]\npos: 1, order: 1";
    };

    Table.compute = function() {
      var id, idx, v, x, _i, _len;
      id = arguments[0], v = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      if (!v.length) {
        return;
      }
      if (!(v[0] instanceof Object)) {
        for (idx = _i = 0, _len = v.length; _i < _len; idx = ++_i) {
          x = v[idx];
          if (!Array.isArray(x)) {
            v[idx] = [x];
          }
        }
      }
      return this.setValAndGet.apply(this, [id].concat(__slice.call(v)));
    };

    Table.prototype.create = function(spec) {
      var h, idx, tr, _base, _i, _len, _name, _ref, _ref1;
      this.spec = spec;
      _ref = this.spec, this.title = _ref.title, this.headings = _ref.headings, this.widths = _ref.widths, this.colCss = _ref.colCss, this.css = _ref.css, this.precision = _ref.precision;
      this.table = $("#" + this.domId());
      if (this.table.length) {
        this.table.remove();
      }
      this.table = $("<table>", {
        id: this.domId(),
        "class": "widget",
        mouseup: (function(_this) {
          return function() {
            return _this.select();
          };
        })(this)
      });
      if (this.title) {
        this.caption = $("<caption>", {
          text: this.title
        });
      }
      this.table.append(this.caption);
      if (this.css) {
        this.table.css(this.css);
      }
      this.colGroup = $("<colgroup>");
      this.table.append(this.colGroup);
      if (this.widths == null) {
        this.widths = 100;
      }
      if (!Array.isArray(this.widths)) {
        this.widths = [this.widths];
      }
      this.setColGroup();
      if (this.headings) {
        tr = $("<tr>");
        this.table.append(tr);
        _ref1 = this.headings;
        for (idx = _i = 0, _len = _ref1.length; _i < _len; idx = ++_i) {
          h = _ref1[idx];
          tr.append("<th>" + h + "</th>");
        }
      }
      this.tbody = $("<tbody>");
      this.table.append(this.tbody);
      this.appendToCanvas(this.table);
      this.tablesFile = $blab.resources.find("tables.json");
      if (!$blab.tableData) {
        $blab.tableData = this.tablesFile ? JSON.parse(this.tablesFile.content) : {};
      }
      if ((_base = $blab.tableData)[_name = this.id] == null) {
        _base[_name] = {};
      }
      this.tableData = $blab.tableData[this.id];
      $(document).on("blabcompute", (function(_this) {
        return function() {
          return _this.setFunctions();
        };
      })(this));
      return this.setVal([[0]]);
    };

    Table.prototype.setColGroup = function(n) {
      var col, css, expand, i, idx, w, _i, _len, _ref, _ref1, _ref2, _results;
      if (n) {
        expand = n && this.widths.length < n && !Array.isArray(this.spec.widths);
        if (!expand) {
          return;
        }
        this.widths = (function() {
          var _i, _results;
          _results = [];
          for (i = _i = 1; 1 <= n ? _i <= n : _i >= n; i = 1 <= n ? ++_i : --_i) {
            _results.push(this.spec.widths);
          }
          return _results;
        }).call(this);
      }
      this.colGroup.empty();
      _ref = this.widths;
      _results = [];
      for (idx = _i = 0, _len = _ref.length; _i < _len; idx = ++_i) {
        w = _ref[idx];
        css = (_ref1 = (_ref2 = this.colCss) != null ? _ref2[idx] : void 0) != null ? _ref1 : {};
        css.width = w;
        col = $("<col>", {
          css: css
        });
        _results.push(this.colGroup.append(col));
      }
      return _results;
    };

    Table.prototype.initialize = function() {};

    Table.prototype.setVal = function(v) {
      var dynamic, editable, idx, invalid, l, o, val, _i, _len;
      this.setUsed();
      if (!(v[0] instanceof Array)) {
        this.v0 = v[0];
        this.first = null;
        return this.setValObject();
      }
      o = {};
      invalid = false;
      for (idx = _i = 0, _len = v.length; _i < _len; idx = ++_i) {
        val = v[idx];
        l = val.length;
        if (l === 0) {
          dynamic = true;
          editable = true;
          o[idx] = val;
        } else if (l === 1 && typeof val[0] === "function") {
          dynamic = true;
          o[idx] = val[0];
        } else {
          invalid = true;
          break;
        }
      }
      if (dynamic) {
        if (invalid) {
          console.log("Invalid table signature.");
          return null;
        } else if (!editable) {
          console.log("Must have at least one editable column.");
          return null;
        } else {
          this.v0 = o;
          this.first = null;
          return this.setValObject();
        }
      } else {
        return this.setValRegular(v);
      }
    };

    Table.prototype.setValRegular = function(v) {
      var d, i, idx, row, tr, val, x, _i, _j, _len, _ref, _ref1;
      this.setColGroup(v.length);
      this.tbody.empty();
      row = [];
      _ref = v[0];
      for (idx = _i = 0, _len = _ref.length; _i < _len; idx = ++_i) {
        x = _ref[idx];
        tr = $("<tr>");
        this.tbody.append(tr);
        for (i = _j = 0, _ref1 = v.length; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; i = 0 <= _ref1 ? ++_j : --_j) {
          d = v[i][idx];
          val = typeof d === "number" ? this.format(d) : d;
          tr.append("<td class='table-cell'>" + val + "</td>");
        }
      }
      this.value = v;
      new TableCellSelector(this.domId());
      return null;
    };

    Table.prototype.setValObject = function() {
      var cell, idx, name, numCols, td, tr, val, x, _base, _base1, _i, _j, _len, _len1, _ref, _ref1, _ref2, _ref3;
      this.editableCells = {};
      this.functionCells = {};
      this.funcs = {};
      this.isFunc = {};
      this.editableCols = [];
      if (this.t == null) {
        this.t = {};
      }
      if (this.editNext == null) {
        this.editNext = {};
      }
      numCols = 0;
      _ref = this.v0;
      for (name in _ref) {
        val = _ref[name];
        numCols++;
        if (!this.first) {
          this.first = name;
        }
        this.isFunc[name] = typeof val === "function";
        if (this.isFunc[name]) {
          if ((_base = this.functionCells)[name] == null) {
            _base[name] = [];
          }
          this.funcs[name] = val;
        } else {
          if ((_base1 = this.editableCells)[name] == null) {
            _base1[name] = [];
          }
          this.editableCols.push(this.setData(name, val));
          if (!this.firstEditableColName) {
            this.firstEditableColName = name;
          }
        }
      }
      this.colNames = (function() {
        var _ref1, _results;
        _ref1 = this.editableCells;
        _results = [];
        for (name in _ref1) {
          cell = _ref1[name];
          _results.push(name);
        }
        return _results;
      }).call(this);
      this.colIdx = {};
      _ref1 = this.colNames;
      for (idx = _i = 0, _len = _ref1.length; _i < _len; idx = ++_i) {
        name = _ref1[idx];
        this.colIdx[name] = idx;
      }
      if (this.currentCol == null) {
        this.currentCol = this.first;
      }
      this.setColGroup(numCols);
      this.tbody.empty();
      _ref2 = this.tableData[this.firstEditableColName];
      for (idx = _j = 0, _len1 = _ref2.length; _j < _len1; idx = ++_j) {
        x = _ref2[idx];
        tr = $("<tr>");
        this.tbody.append(tr);
        _ref3 = this.v0;
        for (name in _ref3) {
          val = _ref3[name];
          td = $("<td>");
          tr.append(td);
          this.setCell(td, name, idx, val);
        }
      }
      new TableCellSelector(this.domId());
      this.checkForFocusCell();
      this.clickNext(this.currentCol);
      this.value = this.v0;
      if (this.editableCols.length === 1) {
        return this.editableCols[0];
      } else {
        return this.editableCols;
      }
    };

    Table.prototype.setData = function(name, val) {
      var idx, v, _base, _i, _len, _ref;
      if (val.length === 0) {
        val = [null];
      }
      if ((_base = this.tableData)[name] == null) {
        _base[name] = val;
      }
      val = this.tableData[name];
      this.t[name] = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = val.length; _i < _len; _i++) {
          v = val[_i];
          _results.push(v);
        }
        return _results;
      })();
      _ref = this.t[name];
      for (idx = _i = 0, _len = _ref.length; _i < _len; idx = ++_i) {
        v = _ref[idx];
        if (v === null) {
          this.t[name][idx] = 0;
        }
      }
      return this.t[name];
    };

    Table.prototype.setCell = function(td, name, idx, v) {
      var cell, d;
      if (this.isFunc[name]) {
        return this.functionCells[name].push(td);
      } else {
        d = this.tableData[name][idx];
        cell = this.createEditableCell(td, name, idx, d);
        return this.editableCells[name].push(cell);
      }
    };

    Table.prototype.createEditableCell = function(container, name, idx, val) {
      return new EditableCell({
        container: container,
        idx: idx,
        val: val,
        callback: (function(_this) {
          return function(val, changed, dir, colDir) {
            return _this.cellAction(name, idx, val, changed, dir, colDir);
          };
        })(this),
        del: (function(_this) {
          return function() {
            return _this.deleteRow(name, idx);
          };
        })(this),
        insert: (function(_this) {
          return function() {
            return _this.insertRow(name, idx);
          };
        })(this),
        paste: (function(_this) {
          return function(idx, val) {
            return _this.paste(name, idx, val);
          };
        })(this),
        clickCell: (function(_this) {
          return function(focus) {
            if (focus == null) {
              focus = true;
            }
            return _this.focusCell = focus ? {
              name: name,
              idx: idx
            } : null;
          };
        })(this)
      });
    };

    Table.prototype.setFunctions = function() {
      var cell, d, error, func, idx, name, v, val, _i, _len, _ref, _ref1;
      if (!this.funcs) {
        return;
      }
      _ref = this.funcs;
      for (name in _ref) {
        func = _ref[name];
        try {
          val = func(this.t);
        } catch (_error) {
          error = _error;
          console.log("====Blabr====", error);
          return;
        }
        _ref1 = this.functionCells[name];
        for (idx = _i = 0, _len = _ref1.length; _i < _len; idx = ++_i) {
          cell = _ref1[idx];
          d = val[idx];
          v = typeof d === "number" ? this.format(d) : d;
          cell.text(v);
        }
      }
    };

    Table.prototype.cellAction = function(name, idx, val, changed, dir, colDir) {
      this.setNext(name, idx, dir, colDir);
      if (this.editNext[name] >= this.editableCells[name].length) {
        this.appendRow(name);
      }
      if (changed) {
        this.tableData[name][idx] = val;
        this.store();
        return this.computeAll();
      } else {
        return this.clickNext(this.currentCol);
      }
    };

    Table.prototype.setNext = function(name, idx, dir, colDir) {
      var m, nextIdx;
      if (dir !== 0 || colDir !== 0) {
        this.focusCell = null;
      }
      if (colDir !== 0) {
        m = this.colIdx[name] + colDir;
        if (m >= 0 && m < this.colNames.length) {
          this.currentCol = this.colNames[m];
          return this.editNext[this.currentCol] = idx;
        }
      } else {
        this.currentCol = name;
        if (dir === 0) {
          return this.editNext[name] = false;
        } else {
          nextIdx = idx + dir;
          if (nextIdx < 0) {
            nextIdx = 0;
          }
          return this.editNext[name] = nextIdx;
        }
      }
    };

    Table.prototype.clickNext = function(name) {
      var next, ok;
      next = this.editNext[name];
      ok = next !== false && next >= 0 && next < this.editableCells[name].length;
      if (ok) {
        return this.editableCells[name][this.editNext[name]].click();
      }
    };

    Table.prototype.appendRow = function(name) {
      var cell, n, _ref;
      _ref = this.editableCells;
      for (n in _ref) {
        cell = _ref[n];
        this.tableData[n].push(null);
      }
      this.store();
      return this.computeAll();
    };

    Table.prototype.insertRow = function(name, idx) {
      var cell, n, _ref;
      this.currentCol = name;
      _ref = this.editableCells;
      for (n in _ref) {
        cell = _ref[n];
        this.tableData[n].splice(idx, 0, null);
        this.editNext[n] = idx;
      }
      this.store();
      return this.computeAll();
    };

    Table.prototype.deleteRow = function(name, idx) {
      var cell, n, _ref;
      this.focusCell = null;
      this.currentCol = name;
      _ref = this.editableCells;
      for (n in _ref) {
        cell = _ref[n];
        this.tableData[n].splice(idx, 1);
      }
      this.editNext[name] = idx > 1 ? idx - 1 : 0;
      this.store();
      return this.computeAll();
    };

    Table.prototype.paste = function(name, idx, val) {
      var i, v, vals, _i, _len;
      vals = val.split(", ").join(" ").split(" ");
      for (i = _i = 0, _len = vals.length; _i < _len; i = ++_i) {
        v = vals[i];
        this.tableData[name][idx + i] = parseFloat(v);
      }
      this.editNext[name] = idx;
      this.store();
      return this.computeAll();
    };

    Table.prototype.checkForFocusCell = function() {
      if (!this.focusCell) {
        return;
      }
      this.currentCol = this.focusCell.name;
      this.editNext[this.currentCol] = this.focusCell.idx;
      return this.focusCell = null;
    };

    Table.prototype.store = function() {
      this.tablesFile.content = JSON.stringify($blab.tableData, null, 2);
      return $.event.trigger("codeNodeChanged");
    };

    Table.prototype.format = function(x) {
      var _ref;
      if (x === 0 || (typeof Number.isInteger === "function" ? Number.isInteger(x) : void 0) && Math.abs(x) < 1e10) {
        return x;
      } else {
        return x.toPrecision((_ref = this.precision) != null ? _ref : 4);
      }
    };

    return Table;

  })(Widget);

  EditableCell = (function() {
    function EditableCell(spec) {
      var _ref;
      this.spec = spec;
      _ref = this.spec, this.container = _ref.container, this.idx = _ref.idx, this.val = _ref.val, this.callback = _ref.callback, this.del = _ref.del, this.insert = _ref.insert, this.paste = _ref.paste, this.clickCell = _ref.clickCell;
      this.disp = this.val === null ? "" : this.val;
      this.div = $("<div>", {
        "class": "editable-table-cell",
        text: this.disp,
        contenteditable: true,
        focus: (function(_this) {
          return function(e) {
            _this.clickCell();
            return setTimeout((function() {
              return _this.selectElementContents(_this.div[0]);
            }), 0);
          };
        })(this),
        mousedown: (function(_this) {
          return function(e) {
            return $.event.trigger("clickInputWidget");
          };
        })(this),
        click: (function(_this) {
          return function(e) {
            e.stopPropagation();
            return _this.click(e);
          };
        })(this),
        keydown: (function(_this) {
          return function(e) {
            return _this.keyDown(e);
          };
        })(this),
        change: (function(_this) {
          return function(e) {
            return _this.change(e);
          };
        })(this),
        blur: (function(_this) {
          return function(e) {
            _this.clickCell(false);
            return setTimeout((function() {
              return _this.change(e);
            }), 100);
          };
        })(this)
      });
      this.div.on("paste", (function(_this) {
        return function(e) {
          _this.div.css({
            color: "white"
          });
          return setTimeout((function() {
            return _this.paste(_this.idx, _this.div.text());
          }), 0);
        };
      })(this));
      this.container.append(this.div);
    }

    EditableCell.prototype.selectElementContents = function(el) {
      var range, sel;
      range = document.createRange();
      range.selectNodeContents(el);
      sel = window.getSelection();
      sel.removeAllRanges();
      return sel.addRange(range);
    };

    EditableCell.prototype.click = function(e) {
      return this.div.focus();
    };

    EditableCell.prototype.reset = function() {
      this.div.empty();
      return this.div.text(this.val === null ? "" : this.val);
    };

    EditableCell.prototype.keyDown = function(e) {
      var backspace, colDir, dir, down, key, left, ret, right, up;
      key = e.keyCode;
      ret = 13;
      backspace = 8;
      left = 37;
      up = 38;
      right = 39;
      down = 40;
      if (key === ret) {
        e.preventDefault();
        if (e.shiftKey) {
          this.insert(this.idx);
        } else {
          this.noChange = true;
          this.done(1);
        }
        return;
      }
      if (key === backspace) {
        if (this.div.text() === "") {
          e.preventDefault();
          this.del(this.idx);
        }
        return;
      }
      if (key !== left && key !== up && key !== right && key !== down) {
        return;
      }
      if (key === up || key === down) {
        e.preventDefault();
      }
      dir = key === down ? 1 : key === up ? -1 : 0;
      colDir = key === right ? 1 : key === left ? -1 : 0;
      return this.done(dir, colDir);
    };

    EditableCell.prototype.change = function(e) {
      if (!this.noChange) {
        return this.done();
      }
    };

    EditableCell.prototype.enterVal = function(v, dir) {
      if (dir == null) {
        dir = 1;
      }
      this.noChange = true;
      this.div.click();
      this.div.text(v);
      return this.done(dir);
    };

    EditableCell.prototype.done = function(dir, colDir) {
      var changed, v, val;
      if (dir == null) {
        dir = 0;
      }
      if (colDir == null) {
        colDir = 0;
      }
      v = this.div.text();
      if (v === "") {
        changed = v !== this.disp;
        val = null;
        this.val = val;
        return this.callback(val, changed, dir, colDir);
      } else {
        val = v ? parseFloat(v) : null;
        changed = val !== this.val;
        if (changed) {
          this.val = val;
        }
        this.disp = this.val;
        return this.callback(val, changed, dir, colDir);
      }
    };

    return EditableCell;

  })();

  TableCellSelector = (function() {
    function TableCellSelector(tableId) {
      var e, _i, _len, _ref;
      this.tableId = tableId;
      this.mouseleave = __bind(this.mouseleave, this);
      this.cell = $("#" + this.tableId + " td");
      _ref = ["click", "blur", "mousedown", "mousemove", "mouseenter", "mouseleave", "mouseup"];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        e = _ref[_i];
        this.cell.unbind(e);
      }
      this.cell.click((function(_this) {
        return function(e) {
          return _this.stop(e);
        };
      })(this));
      this.cell.blur((function(_this) {
        return function(e) {
          return console.log("blur");
        };
      })(this));
      this.cell.mousedown((function(_this) {
        return function(e) {
          return _this.mousedown(e);
        };
      })(this));
      this.cell.mousemove((function(_this) {
        return function(e) {
          return _this.mousemove(e);
        };
      })(this));
      this.cell.mouseleave((function(_this) {
        return function(e) {
          return _this.mouseleave(e);
        };
      })(this));
      this.cell.mouseenter((function(_this) {
        return function(e) {
          return _this.mouseenter(e);
        };
      })(this));
      this.cell.mouseup((function(_this) {
        return function(e) {
          return _this.mouseup(e);
        };
      })(this));
      $(document).on("blabmousedown", (function(_this) {
        return function(e) {
          if (!(_this.down && _this.inTable)) {
            return _this.reset();
          }
        };
      })(this));
      $(document).on("blabmouseup", (function(_this) {
        return function(e) {
          if (!(_this.down && _this.inTable)) {
            return _this.reset();
          }
        };
      })(this));
      $(document).on("blabcopy", (function(_this) {
        return function(e, data) {
          return _this.copy(e, data);
        };
      })(this));
      this.selected = [];
      this.reset();
    }

    TableCellSelector.prototype.reset = function() {
      this.deselectAll();
      this.down = false;
      this.inTable = false;
      this.first = false;
      this.column = null;
      this.start = -1;
      this.end = -1;
      this.selected = [];
      return this.vector = [];
    };

    TableCellSelector.prototype.mousedown = function(e) {
      var row, _ref;
      this.stop(e);
      this.deselectAll();
      this.down = true;
      this.inTable = true;
      this.first = true;
      _ref = this.coord(e), row = _ref[0], this.column = _ref[1];
      this.start = this.end = row;
      return setTimeout(((function(_this) {
        return function() {
          return _this.initFirst(e);
        };
      })(this)), 100);
    };

    TableCellSelector.prototype.initFirst = function(e) {
      if (!(this.first && this.down)) {
        return;
      }
      this.select(e);
      return this.first = false;
    };

    TableCellSelector.prototype.mousemove = function(e) {
      if (!(this.first && this.down)) {
        return;
      }
      this.stop(e);
      return this.initFirst(e);
    };

    TableCellSelector.prototype.mouseleave = function(e) {
      var col, row, _ref;
      if (!this.down) {
        return;
      }
      this.stop(e);
      _ref = this.coord(e), row = _ref[0], col = _ref[1];
      if (col !== this.column) {
        this.reset();
        return;
      }
      this.inTable = false;
      this.lastLeave = e;
      return this.lastLeaveRow = row;
    };

    TableCellSelector.prototype.mouseenter = function(e) {
      var col, row, _ref;
      if (!this.down) {
        return;
      }
      this.stop(e);
      this.inTable = true;
      _ref = this.coord(e), row = _ref[0], col = _ref[1];
      if (col !== this.column) {
        this.reset();
        return;
      }
      this.first = false;
      if (this.lastLeaveRow > row) {
        this.deselect(this.lastLeave);
      }
      if (row > this.end) {
        this.select(e);
      }
      return this.end = row;
    };

    TableCellSelector.prototype.mouseup = function(e) {
      var s;
      this.stop(e);
      this.down = false;
      this.inTable = false;
      if (this.selected.length === 1) {
        this.normal(this.start);
      }
      return this.vector = (function() {
        var _i, _len, _ref, _results;
        _ref = this.selected;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          s = _ref[_i];
          _results.push($(s.target).text());
        }
        return _results;
      }).call(this);
    };

    TableCellSelector.prototype.copy = function(e, data) {
      var string;
      console.log("copy cells", this.tableId, this.vector);
      if (!this.vector.length) {
        return;
      }
      console.log("data", data);
      e = data.original;
      e.preventDefault();
      string = this.vector.join(", ");
      return e.clipboardData.setData('Text', string);
    };

    TableCellSelector.prototype.coord = function(e) {
      var col, p, row, t, td, tr;
      t = $(e.target);
      p = t.parent();
      if (this.isEditable(e)) {
        td = p;
        tr = td.parent();
      } else {
        td = t;
        tr = p;
      }
      row = tr.index();
      col = td.index();
      return [row, col];
    };

    TableCellSelector.prototype.deselectAll = function() {
      var s, _i, _len, _ref;
      if (!this.selected.length) {
        return;
      }
      _ref = this.selected;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        s = _ref[_i];
        this.normal(s);
      }
      return this.selected = [];
    };

    TableCellSelector.prototype.select = function(e) {
      this.highlight(e);
      return this.selected.push(e);
    };

    TableCellSelector.prototype.deselect = function(e) {
      this.selected.pop();
      return this.normal(e);
    };

    TableCellSelector.prototype.highlight = function(e) {
      return $(e.target).css({
        background: "rgb(180, 213, 254)"
      });
    };

    TableCellSelector.prototype.normal = function(e) {
      return $(e.target).css({
        background: ""
      });
    };

    TableCellSelector.prototype.isEditable = function(e) {
      return $(e.target).attr("class") === "editable-table-cell";
    };

    TableCellSelector.prototype.stop = function(e) {
      e.preventDefault();
      return e.stopPropagation();
    };

    return TableCellSelector;

  })();

  Plot = (function(_super) {
    __extends(Plot, _super);

    function Plot() {
      return Plot.__super__.constructor.apply(this, arguments);
    }

    Plot.handle = "plot";

    Plot.initSpec = function(id) {
      return "title: \"" + id + "\"\nwidth: 300, height: 200\nxlabel: \"x\", ylabel: \"y\"\n# xaxis: {min: 0, max: 1}\n# yaxis: {min: 0, max: 1}\nseries: {lines: lineWidth: 1}\ncolors: [\"red\", \"blue\"]\ngrid: {backgroundColor: \"white\"}\npos: 1, order: 1";
    };

    Plot.compute = function() {
      var id, v;
      id = arguments[0], v = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return this.setVal.apply(this, [id].concat(__slice.call(v)));
    };

    Plot.prototype.create = function(spec) {
      var _ref, _ref1, _ref2;
      this.spec = spec;
      _ref = this.spec, this.title = _ref.title, this.width = _ref.width, this.height = _ref.height, this.xlabel = _ref.xlabel, this.ylabel = _ref.ylabel, this.css = _ref.css;
      this.outer = $("<div>", {
        css: {
          textAlign: "center"
        },
        mouseup: (function(_this) {
          return function() {
            return _this.select();
          };
        })(this)
      });
      this.plot = $("#" + this.domId());
      if (this.plot.length) {
        this.plot.remove();
      }
      this.plot = $("<div>", {
        id: this.domId(),
        "class": "puzlet-plot",
        css: {
          width: (_ref1 = this.width) != null ? _ref1 : 400,
          height: (_ref2 = this.height) != null ? _ref2 : 200
        },
        mouseup: (function(_this) {
          return function() {
            return _this.select();
          };
        })(this)
      });
      if (this.title) {
        this.caption = $("<div>", {
          html: this.title,
          css: {
            fontSize: "10pt",
            marginBottom: -8
          }
        });
        this.outer.append(this.caption);
      }
      this.outer.append(this.plot);
      if (this.css) {
        this.plot.css(this.css);
      }
      this.appendToCanvas(this.outer);
      return this.setVal([[0], [0]]);
    };

    Plot.prototype.initialize = function() {};

    Plot.prototype.setVal = function(v) {
      var X, Y, d, k, l, lol, m, maxRows, o, params, xRow, yRow, _base, _i;
      this.setUsed();
      this.value = v;
      params = this.spec;
      if ((_base = params.series).shadowSize == null) {
        _base.shadowSize = 0;
      }
      if (params.series == null) {
        params.series = {
          color: "#55f"
        };
      }
      this.setAxes(params);
      lol = function(u) {
        var z;
        if (u[0].length != null) {
          z = u;
        } else {
          z = [];
          z.push(u);
        }
        return z;
      };
      X = lol(v[0]);
      Y = lol(v[1]);
      maxRows = Math.max(X.length, Y.length);
      d = [];
      for (k = _i = 0; 0 <= maxRows ? _i < maxRows : _i > maxRows; k = 0 <= maxRows ? ++_i : --_i) {
        xRow = Math.min(k, X.length - 1);
        yRow = Math.min(k, Y.length - 1);
        l = numeric.transpose([X[xRow], Y[yRow]]);
        d.push(l);
      }
      this.flot = $.plot(this.plot, d, params);
      o = this.flot.getPlotOffset();
      m = (this.plot.parent().width() - this.plot.width() - o.left + o.right) / 2;
      return this.plot.css({
        marginLeft: m
      });
    };

    Plot.prototype.setAxes = function(params) {
      var _ref, _ref1, _ref2, _ref3, _ref4, _ref5;
      if (params.xaxis == null) {
        params.xaxis = {};
      }
      if (params.yaxis == null) {
        params.yaxis = {};
      }
      if (params.xlabel) {
        if ((_ref = params.xaxis) != null) {
          _ref.axisLabel = params.xlabel;
        }
      }
      if (params.ylabel) {
        if ((_ref1 = params.yaxis) != null) {
          _ref1.axisLabel = params.ylabel;
        }
      }
      if ((_ref2 = params.xaxis) != null) {
        if (_ref2.axisLabelUseCanvas == null) {
          _ref2.axisLabelUseCanvas = true;
        }
      }
      if ((_ref3 = params.yaxis) != null) {
        if (_ref3.axisLabelUseCanvas == null) {
          _ref3.axisLabelUseCanvas = true;
        }
      }
      if ((_ref4 = params.xaxis) != null) {
        if (_ref4.axisLabelPadding == null) {
          _ref4.axisLabelPadding = 10;
        }
      }
      return (_ref5 = params.yaxis) != null ? _ref5.axisLabelPadding != null ? _ref5.axisLabelPadding : _ref5.axisLabelPadding = 10 : void 0;
    };

    return Plot;

  })(Widget);

  AxesLabels = (function() {
    function AxesLabels(container, params) {
      this.container = container;
      this.params = params;
      if (this.params.xlabel) {
        this.xaxisLabel = this.appendLabel(this.params.xlabel, "xaxisLabel");
      }
      if (this.params.ylabel) {
        this.yaxisLabel = this.appendLabel(this.params.ylabel, "yaxisLabel");
      }
    }

    AxesLabels.prototype.appendLabel = function(txt, className) {
      var label;
      label = $("<div>", {
        text: txt
      });
      label.addClass("axisLabel");
      label.addClass(className);
      this.container.append(label);
      return label;
    };

    AxesLabels.prototype.position = function() {
      var _ref, _ref1;
      if ((_ref = this.xaxisLabel) != null) {
        _ref.css({
          marginLeft: (-this.xaxisLabel.width() / 2 + 10) + "px",
          marginBottom: "-20px"
        });
      }
      return (_ref1 = this.yaxisLabel) != null ? _ref1.css({
        marginLeft: "-27px",
        marginTop: (this.yaxisLabel.width() / 2 - 10) + "px"
      }) : void 0;
    };

    return AxesLabels;

  })();

  $blab.baseWidgets = [Input, Slider, Table, Plot];

}).call(this);
